import {accountApi as api} from './account-backend.js';
const $=id=>document.getElementById(id);
let profile=null,creating=false,saveTimer=0,pendingPatch={},saving=false;
const safe=fn=>async()=>{try{await fn();}catch(error){setStatus(error.message,true);}};
const dialog=document.createElement('dialog');dialog.id='account';dialog.innerHTML='<form method="dialog" id="account-form" novalidate><div class="settings-heading"><div><p class="overline">NEON BREACH ID</p><h2 id="account-title">Sign in.</h2></div><button id="account-close" type="button" aria-label="Close account" class="icon-button">×</button></div><p id="account-copy" class="status">NEON BREACH accounts use email and password. No email verification for now; password-reset email is not available. Save your password securely. Previous site accounts have not transferred.</p><section id="profile-panel" class="hidden"><div class="profile-hero"><span class="profile-mark">N/B</span><div><small>OPERATOR PROFILE</small><strong id="profile-name">RANGER</strong><em id="profile-rank">UNRANKED</em></div></div><div class="profile-grid"><div><b id="profile-matches">0</b><small>MATCHES</small></div><div><b id="profile-wins">0</b><small>WINS</small></div><div><b id="profile-kills">0</b><small>ELIMS</small></div><div><b id="profile-best">0</b><small>BEST STREAK</small></div></div><label for="skin-select">OPERATOR SKIN</label><select id="skin-select"><option value="mint">Mint circuit</option><option value="solar">Solar flare</option><option value="violet">Violet pulse</option><option value="crimson">Crimson vector</option><option value="carbon">Carbon ghost</option></select></section><section id="auth-panel"><label for="account-email">EMAIL</label><input id="account-email" type="email" autocomplete="email" required><label for="account-username">CALLSIGN (NEW ACCOUNTS)</label><input id="account-username" maxlength="16" autocomplete="username" spellcheck="false" required><label for="account-password">PASSWORD</label><input id="account-password" type="password" minlength="10" autocomplete="current-password" required><button id="account-submit" class="primary" type="submit">SIGN IN ↗</button><button id="account-switch" class="text-button" type="button">NEED AN ACCOUNT? CREATE ONE</button></section><p id="account-status" class="status" role="status"></p><section id="social-panel" class="hidden"><div class="divider"><span>SQUAD NETWORK</span></div><label for="friend-name">ADD FRIEND</label><div class="join-row"><input id="friend-name" maxlength="16" placeholder="CALLSIGN"><button id="friend-add" type="button">ADD</button></div><div id="friend-list" class="friend-list"></div></section><button id="account-logout" class="text-button hidden" type="button">SIGN OUT</button></form>';
document.body.append(dialog);
const openButton=document.createElement('button');openButton.id='account-open';openButton.className='secondary compact';openButton.textContent='ACCOUNT';document.querySelector('.header-right')?.prepend(openButton);
const downloads=document.createElement('a');downloads.className='secondary compact download-link';downloads.href='./downloads.html';downloads.textContent='DESKTOP CLIENT';document.querySelector('.header-right')?.prepend(downloads);
const music=document.createElement('div');music.innerHTML='<label for="music-volume">MUSIC <output id="music-volume-value">35%</output></label><input type="range" id="music-volume" min="0" max="100" value="35">';$('volume')?.parentElement?.insertBefore(music,$('volume').nextSibling);
function setStatus(text,error=false){$('account-status').textContent=text;$('account-status').classList.toggle('error',error);}
function render(){const active=!!profile;openButton.textContent=active?profile.username:'ACCOUNT';$('profile-panel').classList.toggle('hidden',!active);$('auth-panel').classList.toggle('hidden',active);$('social-panel').classList.toggle('hidden',!active);$('account-logout').classList.toggle('hidden',!active);if(active){const stats=profile.stats||{};$('nickname').value=profile.username;$('profile-name').textContent=profile.username;$('profile-rank').textContent=(stats.wins||0)>=20?'RIFT VANGUARD':(stats.matches||0)>=5?'ARENA RUNNER':'UNRANKED';$('profile-matches').textContent=stats.matches||0;$('profile-wins').textContent=stats.wins||0;$('profile-kills').textContent=stats.kills||0;$('profile-best').textContent=stats.best||0;$('skin-select').value=profile.skin||'mint';renderFriends();}}
async function refresh(){try{profile=(await api('/api/me')).user;const stored=profile.settings||{};window.dispatchEvent(new CustomEvent('neon-account',{detail:{profile,settings:stored}}));render();presence();return profile;}catch{profile=null;render();return null;}}
function show(){creating=false;$('account-submit').textContent='SIGN IN ↗';$('account-switch').textContent='NEED AN ACCOUNT? CREATE ONE';$('account-password').autocomplete='current-password';setStatus('');$('account-title').textContent=profile?'Operator profile.':'Sign in.';$('account-copy').textContent=profile?'Loadout, career, and squad network. Game controls remain in Settings.':'NEON BREACH accounts use email and password. No email verification for now; password-reset email is not available. Save your password securely. Previous site accounts have not transferred.';$('account-username').value=profile?.username||'';$('account-password').value='';render();dialog.showModal();}
async function renderFriends(){if(!profile)return;try{const data=await api('/api/friends'),root=$('friend-list');root.replaceChildren(...data.friends.map(f=>{const row=document.createElement('div');row.className='friend-row';const label=document.createElement('span');label.textContent=f.username+' · '+(f.state==='accepted'?(f.online?'ONLINE':'OFFLINE'):f.direction==='incoming'?'REQUEST RECEIVED':'REQUEST SENT');row.append(label);if(f.state==='pending'&&f.direction==='incoming'){const b=document.createElement('button');b.type='button';b.textContent='ACCEPT';b.onclick=safe(async()=>{await api('/api/friends/respond',{method:'POST',body:JSON.stringify({id:f.id,accept:true})});renderFriends();});row.append(b);const decline=document.createElement('button');decline.type='button';decline.textContent='DECLINE';decline.onclick=safe(async()=>{await api('/api/friends/respond',{method:'POST',body:JSON.stringify({id:f.id,accept:false})});renderFriends();});row.append(decline);}if(f.state==='accepted'){const b=document.createElement('button');b.type='button';b.textContent='INVITE';b.disabled=!window.neonRoom?.().code||window.neonRoom?.().state==='match';b.title=b.disabled?'Create or join a lobby before inviting.':'';b.onclick=safe(async()=>{const room=window.neonRoom?.().code;if(!room)throw Error('Create a room before inviting.');await api('/api/friends/invite',{method:'POST',body:JSON.stringify({username:f.username,room})});setStatus('Invite sent to '+f.username+'.');});row.append(b);}return row;}),...data.invites.map(i=>{const row=document.createElement('div'),b=document.createElement('button');row.className='friend-row';row.append(document.createTextNode(i.sender+' invited you to '+i.room_code));b.type='button';b.textContent='JOIN';b.onclick=()=>{location.hash='room='+i.room_code;dialog.close();location.reload();};row.append(b);return row;}));}catch(error){setStatus(error.message,true);}}
$('account-form').addEventListener('submit',async event=>{event.preventDefault();if(profile)return;const email=$('account-email').value.trim(),username=$('account-username').value,password=$('account-password').value;try{$('account-submit').disabled=true;const data=await api(creating?'/api/auth/signup':'/api/auth/login',{method:'POST',body:JSON.stringify({email,username,password})});profile=data.user;await refresh();setStatus(creating?'Account created. Your profile will follow you.':'Signed in.');setTimeout(()=>dialog.close(),500);}catch(error){setStatus(error.message,true);}finally{$('account-submit').disabled=false;}});
$('account-close').onclick=()=>dialog.close();$('account-switch').onclick=()=>{creating=!creating;$('account-password').autocomplete=creating?'new-password':'current-password';$('account-title').textContent=creating?'Create account.':'Sign in.';$('account-submit').textContent=creating?'CREATE ACCOUNT ↗':'SIGN IN ↗';$('account-switch').textContent=creating?'ALREADY HAVE AN ACCOUNT? SIGN IN':'NEED AN ACCOUNT? CREATE ONE';setStatus(creating?'Use 3–16 letters, numbers, _ or -, plus a 10+ character password.':'');};
$('friend-add').onclick=async()=>{try{await api('/api/friends/request',{method:'POST',body:JSON.stringify({username:$('friend-name').value})});$('friend-name').value='';setStatus('Friend request sent.');renderFriends();}catch(error){setStatus(error.message,true);}};
$('account-logout').onclick=safe(async()=>{await flush();await api('/api/auth/logout',{method:'POST'});profile=null;pendingPatch={};clearTimeout(saveTimer);render();dialog.close();});openButton.onclick=show;$('skin-select').onchange=()=>save({skin:$('skin-select').value});
function save(patch={}){if(!profile)return;pendingPatch={...pendingPatch,...patch};clearTimeout(saveTimer);saveTimer=setTimeout(flush,400);}
async function flush(){if(!profile||saving)return;saving=true;const owner=profile.id,patch=pendingPatch;pendingPatch={};try{const settings=window.neonSettings?.()||{};const saved=await api('/api/profile',{method:'PATCH',body:JSON.stringify({skin:patch.skin||$('skin-select').value,settings,stats:patch.stats})});if(profile?.id===owner){profile=saved.user;render();setStatus('Profile saved.');}}catch(error){pendingPatch={...patch,...pendingPatch};setStatus('Could not save your profile. Check your connection and try again.',true);}finally{saving=false;}}
async function presence(){if(!profile)return;try{await api('/api/presence',{method:'POST',body:'{}'});if(dialog.open)await renderFriends();}catch{}}
setInterval(presence,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){presence();if(Object.keys(pendingPatch).length)flush();}});
window.neonAccount={refresh,saveSettings:()=>save(),saveStats:stats=>save({stats}),saveSkin:skin=>save({skin}),get profile(){return profile;}};refresh();
