import {KEY_DEFAULTS,PAD_DEFAULTS,ACTION_NAMES,PAD_LABELS,keyLabel,rebind} from './control-bindings.js';
export function mountBindings(bindings,onChange){
 const dialog=document.createElement('dialog');dialog.id='bind-picker';dialog.innerHTML='<div class="settings-heading"><h2>Choose a control</h2><button type="button" aria-label="Cancel binding">×</button></div><p id="bind-help"></p><p id="bind-status" role="status"></p><div class="pad-bind-options"></div><button type="button" class="secondary" id="bind-cancel">CANCEL</button>';document.body.append(dialog);let editing=null,opened=0;
 const close=()=>{editing=null;dialog.close();};dialog.querySelector('.settings-heading button').onclick=close;dialog.querySelector('#bind-cancel').onclick=close;dialog.addEventListener('close',()=>editing=null);
 function apply(value){if(!editing)return;const {device,action}=editing,result=rebind(bindings,device,action,value);if(!result){dialog.querySelector('#bind-status').textContent='That control is reserved. Choose another; Esc cancels.';return;}onChange();render();close();status[device].textContent=ACTION_NAMES[action]+' → '+(device==='kbm'?keyLabel(value):PAD_LABELS[value])+(result.swapped?' · Swapped with '+ACTION_NAMES[result.swapped]+'.':'.');}
 const lists={},status={};for(const device of ['kbm','ps5']){const root=document.getElementById(device==='kbm'?'controls-kbm':'controls-ps5'),section=document.createElement('section');section.className='binding-editor';const title=document.createElement('h3');title.textContent=device==='kbm'?'Keyboard & mouse bindings':'Controller gameplay bindings';const note=document.createElement('p');note.className='status';note.textContent=device==='kbm'?'Select an action, then press a key or mouse button. Conflicts swap assignments. Esc remains the menu key; mouse wheel switches weapons.':'Select an action, then press a controller button or choose its tile. Conflicts swap assignments. Sticks and menu navigation stay standard; Options opens the menu.';const list=lists[device]=document.createElement('div');list.className='binding-list';status[device]=document.createElement('p');status[device].className='status';status[device].setAttribute('role','status');const reset=document.createElement('button');reset.type='button';reset.className='secondary';reset.textContent='RESET '+(device==='kbm'?'KEYBOARD & MOUSE':'CONTROLLER');reset.onclick=()=>{bindings[device]={...(device==='kbm'?KEY_DEFAULTS:PAD_DEFAULTS)};onChange();render();status[device].textContent='Default controls restored.';};section.append(title,note,list,status[device],reset);root.append(section);}
 function render(){for(const device of ['kbm','ps5']){lists[device].replaceChildren();for(const [action,value]of Object.entries(bindings[device])){const b=document.createElement('button');b.type='button';b.dataset.binding=action;b.dataset.device=device;const name=document.createElement('span'),key=document.createElement('kbd');name.textContent=ACTION_NAMES[action];key.textContent=device==='kbm'?keyLabel(value):PAD_LABELS[value];b.append(name,key);b.onclick=()=>{editing={device,action};opened=performance.now();dialog.querySelector('h2').textContent=ACTION_NAMES[action];dialog.querySelector('#bind-status').textContent='';dialog.querySelector('#bind-help').textContent=device==='kbm'?'Press a key or mouse button. Escape cancels.':'Press a controller button or choose below. Options cancels.';const grid=dialog.querySelector('.pad-bind-options');grid.replaceChildren();if(device==='ps5')for(const [id,label]of Object.entries(PAD_LABELS)){const option=document.createElement('button');option.type='button';option.className='secondary';option.textContent=label;option.onclick=()=>apply(+id);grid.append(option);}dialog.showModal();};lists[device].append(b);}}
 const kb=document.getElementById('controls-kbm');if(!kb.querySelector('.keyboard-layout')){const img=document.createElement('img');img.className='keyboard-layout';img.src='./keyboard-mouse.svg';img.alt='Keyboard with staggered letter rows, separate arrow keys, and a five-button mouse with scroll wheel.';kb.prepend(img);}document.querySelector('#controls-ps5 .pad-bindings')?.remove();kb.querySelector('.control-list')?.remove();kb.querySelector('.keyboard-diagram')?.remove();const notes=kb.querySelectorAll(':scope > .status');if(notes[0])notes[0].textContent='Hold Shift with your ping control for danger, or Alt for regroup. Pings expire after 8 seconds.';const ps=document.getElementById('controls-ps5');const psNote=[...ps.querySelectorAll(':scope > .status')].find(p=>p.textContent.startsWith('In match:'));if(psNote)psNote.textContent='Hold Aim with your location ping for danger. Pings are private to your team in team modes.';
 }
 document.addEventListener('keydown',e=>{if(!editing)return;e.stopImmediatePropagation();if(e.code==='Escape'){e.preventDefault();close();return;}if(editing.device==='kbm'){e.preventDefault();if(!e.repeat)apply(e.code);}},true);
 document.addEventListener('mousedown',e=>{if(editing?.device!=='kbm'||dialog.querySelector('button')?.contains(e.target)||e.target.closest('#bind-cancel'))return;e.preventDefault();e.stopImmediatePropagation();apply('Mouse'+e.button);},true);
 document.addEventListener('contextmenu',e=>{if(editing)e.preventDefault();},true);
 render();return {capturePad(frame){if(!editing||editing.device!=='ps5')return false;if(performance.now()-opened<180)return true;const button=frame?.pressed?.findIndex(Boolean);if(button===9)close();else if(button>=0)apply(button);return true;},refresh:render};
}
