import {WEAPONS,WEAPON_RANGES} from './core.js';
import {MAPS} from './rules.js';
export const SKINS={mint:'Mint circuit',solar:'Solar flare',violet:'Violet pulse',crimson:'Crimson vector',carbon:'Carbon ghost'};
const descriptions={archive:'48 × 38m · A white-and-teal research archive with enclosed stacks, covered labs and a bright central atrium. Tight corners favor deliberate close-range pushes.',dockyard:'48 × 64m · A storm-blue freight terminal. Long cargo lanes, container cover and raised loading gantries create wide flanks and changing engagement ranges.',rift:'Balanced sightlines, a reactor centerpiece, and elevated flanking routes.',foundry:'48 × 48m · Four machine rooms, twin upper galleries and four staircases. Fight underneath the galleries or flank above the loading aisle.',citadel:'64 × 38m · Wide courtyards, two keeps and an elevated skybridge. Cross above the arena or slip through the underpass.'};
const $=id=>document.getElementById(id);
export function mountGallery(){
 const modal=document.createElement('dialog');modal.id='collection';modal.innerHTML='<div class="settings-heading"><div><p class="overline">FIELD MANUAL</p><h2 id="collection-title">Armory.</h2></div><button type="button" class="icon-button" aria-label="Close previews">×</button></div><p id="collection-copy" class="status"></p><div class="preview-grid" id="collection-grid"></div>';
 document.body.append(modal);modal.querySelector('button').onclick=()=>modal.close();
 function maps(target){const setup=window.neonMatchSetup;const selected=setup?setup.current.map:target.value;const editable=setup?setup.editable:!target.disabled;$('collection-title').textContent='Choose your arena.';$('collection-copy').textContent='Choose the arena for your match setup. Your selection carries into the room and solo practice.';$('collection-grid').replaceChildren(...Object.entries(MAPS).map(([id,name])=>{const b=document.createElement('button');b.type='button';b.className='preview-card';b.setAttribute('aria-pressed',String(selected===id));b.innerHTML=`<img src="./previews/map-${id}.png" alt="${name} arena overview"><strong>${name}</strong><p>${descriptions[id]}</p><small>${selected===id?'SELECTED':'SELECT ARENA →'}</small>`;b.disabled=!editable;b.onclick=()=>{if(setup){if(!setup.chooseMap(id))return;}else{target.value=id;target.dispatchEvent(new Event('change',{bubbles:true}));}sync();window.addEventListener('neon-setup-change',sync);modal.close();};return b;}));modal.showModal();}
 window.neonMaps=()=>maps($('room-map'));const mapSelect=$('room-map');mapSelect.hidden=true;const mapButton=document.createElement('button');mapButton.type='button';mapButton.className='map-launch';mapSelect.after(mapButton);mapButton.onclick=()=>maps(mapSelect);
 function sync(){mapButton.innerHTML=`<img src="./previews/map-${mapSelect.value}.png" alt=""><span><small>SELECTED ARENA · CHANGE</small><b>${MAPS[mapSelect.value]}</b></span>`;}sync();
 const live=$('live-map');const browse=document.createElement('button');browse.type='button';browse.className='text-button';browse.textContent='PREVIEW MAPS';live.after(browse);browse.onclick=()=>maps(live);
 const armory=document.createElement('button');armory.id='armory-open';armory.className='secondary compact';armory.textContent='ARMORY';document.querySelector('.header-right').prepend(armory);armory.onclick=()=>{$('collection-title').textContent='Know your arsenal.';$('collection-copy').textContent='Choose your starting weapon. Room rules determine which weapons are available. Use 1–5, the mouse wheel, or Triangle to switch.';$('collection-grid').replaceChildren(...WEAPONS.map((w,i)=>{const card=document.createElement('article');card.className='preview-card';card.innerHTML=`<img src="./previews/gun-${i}.png" alt="${w.name}"><small>SLOT ${i+1} · ${w.auto?'AUTOMATIC':'SEMI-AUTOMATIC'}</small><strong>${w.short}</strong><p>${['Versatile mid-range pressure. Hold fire for sustained bursts.','Nine pellets per shot. Close the distance for maximum impact.','Precision shots and a magnified scope. Aim for the head.','Fast, compact automatic fire. Strong up close; wider spread at range.','A deliberate, hard-hitting sidearm. Accurate taps reward steady aim.'][i]}</p><dl><div><dt>Damage</dt><dd>${w.damage}${w.pellets>1?' × '+w.pellets:''}</dd></div><div><dt>Magazine</dt><dd>${w.cap}</dd></div><div><dt>Reload</dt><dd>${w.reload}s</dd></div><div><dt>Full damage</dt><dd>${WEAPON_RANGES[i][0]}m</dd></div></dl>`;const listen=document.createElement('button');listen.type='button';listen.className='text-button';listen.textContent='LISTEN TO WEAPON';listen.onclick=()=>window.dispatchEvent(new CustomEvent('neon-preview-sound',{detail:i}));const equip=document.createElement('button');equip.className='secondary';equip.textContent=window.neonSettings?.().preferredWeapon===i?'STARTING WEAPON':'SET AS STARTING WEAPON';equip.onclick=()=>{window.dispatchEvent(new CustomEvent('neon-customize',{detail:{preferredWeapon:i}}));armory.onclick();};card.append(listen,equip);return card;}));if(!modal.open)modal.showModal();};
}
