import {WEAPONS} from './core.js';
import {MAPS} from './rules.js';
export const SKINS={mint:'Mint circuit',solar:'Solar flare',violet:'Violet pulse',crimson:'Crimson vector',carbon:'Carbon ghost'};
const descriptions={rift:'Balanced sightlines, a reactor centerpiece, and elevated flanking routes.',foundry:'Offset barricades create diagonal fights and close-range ambushes.',citadel:'Tall central cover splits the arena into distinct firing lanes.'};
const $=id=>document.getElementById(id);
export function mountGallery(){
 const modal=document.createElement('dialog');modal.id='collection';modal.innerHTML='<div class="settings-heading"><div><p class="overline">FIELD MANUAL</p><h2 id="collection-title">Armory.</h2></div><button type="button" class="icon-button" aria-label="Close previews">×</button></div><p id="collection-copy" class="status"></p><div class="preview-grid" id="collection-grid"></div>';
 document.body.append(modal);modal.querySelector('button').onclick=()=>modal.close();
 function maps(target){$('collection-title').textContent='Choose your arena.';$('collection-copy').textContent='Actual in-game environments. Select a map to use it for your next room or practice match.';$('collection-grid').replaceChildren(...Object.entries(MAPS).map(([id,name])=>{const b=document.createElement('button');b.type='button';b.className='preview-card';b.setAttribute('aria-pressed',String(target.value===id));b.innerHTML=`<img src="./previews/map-${id}.png" alt="${name} arena overview"><strong>${name}</strong><p>${descriptions[id]}</p><small>${target.value===id?'SELECTED':'SELECT ARENA →'}</small>`;b.onclick=()=>{target.value=id;target.dispatchEvent(new Event('change',{bubbles:true}));sync();modal.close();};return b;}));modal.showModal();}
 const mapSelect=$('room-map');mapSelect.hidden=true;const mapButton=document.createElement('button');mapButton.type='button';mapButton.className='map-launch';mapSelect.after(mapButton);mapButton.onclick=()=>maps(mapSelect);
 function sync(){mapButton.innerHTML=`<img src="./previews/map-${mapSelect.value}.png" alt=""><span><small>SELECTED ARENA · CHANGE</small><b>${MAPS[mapSelect.value]}</b></span>`;}sync();
 const live=$('live-map');const browse=document.createElement('button');browse.type='button';browse.className='text-button';browse.textContent='PREVIEW MAPS';live.after(browse);browse.onclick=()=>maps(live);
 const armory=document.createElement('button');armory.id='armory-open';armory.className='secondary compact';armory.textContent='ARMORY';document.querySelector('.header-right').prepend(armory);armory.onclick=()=>{$('collection-title').textContent='Know your arsenal.';$('collection-copy').textContent='All three weapons are available every match. Press 1 / 2 / 3, or Triangle on your controller, to switch. These previews use the game’s weapon models.';$('collection-grid').replaceChildren(...WEAPONS.map((w,i)=>{const card=document.createElement('article');card.className='preview-card';card.innerHTML=`<img src="./previews/gun-${i}.png" alt="${w.name}"><small>SLOT ${i+1} · ${w.auto?'AUTOMATIC':'SEMI-AUTOMATIC'}</small><strong>${w.short}</strong><p>${['Versatile mid-range pressure. Hold fire for sustained bursts.','Nine pellets per shot. Close the distance for maximum impact.','Precision shots and a magnified scope. Aim for the head.'][i]}</p><dl><div><dt>Damage</dt><dd>${w.damage}${w.pellets>1?' × '+w.pellets:''}</dd></div><div><dt>Magazine</dt><dd>${w.cap}</dd></div><div><dt>Reload</dt><dd>${w.reload}s</dd></div></dl>`;return card;}));modal.showModal();};
}
