import * as T from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {createArena,makeSoldier,makeViewWeapons} from './arena.js';
import {WEAPONS,BLOCKS,setArenaMap,makePlayer,movePlayer,resetLife,packetPlayer,validState,hitPlayer,wallDistance,direction,clamp,lerp,angleLerp} from './core.js';
import {JUMP_PADS,POWER_TYPES,POWER_NAMES,createPowerNodes,tickPowers,activateBoost,grantPower,applyDamage,awardElimination,packCombat,receiveCombat,accuracy} from './systems.js';
import {createPowerVisuals} from './power-visuals.js';
import {MODES,MAPS,HILLS,TEAM_NAMES,normalizeRules,points,hillState,tickHill,sameTeam,teamCounts,canJoinTeam,canStartRoom} from './rules.js';
import {ControllerInput} from './controller.js';
import {DuelLink} from './room-network.js';
import './account.js';

const $=id=>document.getElementById(id),show=id=>$(id).classList.remove('hidden'),hide=id=>$(id).classList.add('hidden');
const mapChoice=document.createElement('div');mapChoice.className='room-options';mapChoice.innerHTML='<div><label for="room-map">ARENA MAP</label><select id="room-map"><option value="rift">Orbital Rift · balanced core</option><option value="foundry">Solar Foundry · diagonal cover</option><option value="citadel">Eclipse Citadel · central lanes</option></select></div>';document.querySelector('.play-panel .room-options')?.after(mapChoice);document.querySelector('.mode-line span:last-child').textContent='WINDOWS + MAC / DESKTOP BETA';for(const note of document.querySelectorAll('#settings .status'))if(note.textContent.includes('Installing uses'))note.textContent='For more FPS: choose Low-spec, set render scale to 75%, and turn shadows and effects off. Your desktop installer uses the same renderer and these GPU settings.';
const settings={quality:'auto',sensitivity:1,fov:85,volume:.7,musicVolume:.35,atmosphere:'aurora',reticle:'mint',motion:'full',difficulty:'normal',inputMode:'auto',padSensitivity:1.2,deadzone:.14,invertY:false,rumble:true,renderPercent:100,shadowQuality:'auto',effects:'full',frameLimit:0};try{Object.assign(settings,JSON.parse(localStorage.getItem('neon-breach-settings-v2')||'{}'));$('nickname').value=localStorage.getItem('neon-breach-name')||'Ranger'}catch{}window.neonSettings=()=>({...settings});window.addEventListener('neon-account',event=>{const cloud=event.detail.settings||{};Object.assign(settings,cloud);if(event.detail.profile?.username)$('nickname').value=event.detail.profile.username;syncCloudSettings();});
let renderer;
try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch{$('loading-note').textContent='WebGL 2 is unavailable. Enable hardware acceleration in Chrome or Edge, then reload.';throw new Error('WebGL 2 unavailable');}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.outputColorSpace=T.SRGBColorSpace;
renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Neon Breach first-person game');$('viewport').appendChild(renderer.domElement);
const arena=createArena(renderer),scene=arena.scene;const camera=new T.PerspectiveCamera(85,innerWidth/innerHeight,.07,260);camera.rotation.order='YXZ';function applyMap(map){setArenaMap(map);arena.setMap(map);}
const target=new T.WebGLRenderTarget(innerWidth,innerHeight,{type:T.HalfFloatType,samples:4});const composer=new EffectComposer(renderer,target);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.35,.5,1.4);composer.addPass(bloom);composer.addPass(new OutputPass());
const view=makeViewWeapons();view.scene.environment=scene.environment;view.scene.environmentIntensity=.5;
const rivalModel=makeSoldier(0xff9b70);scene.add(rivalModel.root);rivalModel.root.visible=false;
const cells=[{x:-18,y:2.2,z:4,cool:0},{x:18,y:2.2,z:-4,cool:0}];
const cellMaterial=new T.MeshStandardMaterial({color:0x8dffd1,emissive:0x54ffac,emissiveIntensity:1.3,metalness:.35,roughness:.2});
for(const cell of cells){const root=new T.Group();root.position.set(cell.x,cell.y+.55,cell.z);const a=new T.Mesh(new T.BoxGeometry(.14,.5,.14),cellMaterial),b=new T.Mesh(new T.BoxGeometry(.5,.14,.14),cellMaterial);root.add(a,b);const orbit=new T.Mesh(new T.TorusGeometry(.5,.015,6,40),cellMaterial);orbit.rotation.x=Math.PI/2;orbit.position.y=-.47;root.add(orbit);scene.add(root);cell.mesh=root;}
const powerNodes=createPowerNodes(),powerVisuals=createPowerVisuals(scene,powerNodes);
let medalTime=0,rivalPing=0,objectiveNotice=false,statsSaved=false,hudClock=0,renderScale=1.5,perfSeconds=0,perfFrames=0;
const radar=$('radar').getContext('2d');
const controller=new ControllerInput();let activeInput=settings.inputMode==='ps5'?'ps5':'kbm',padFrame=null,padContext='',padUiClock=0,padStatus='',menuRepeat=0,menuDirection=0;
const link=new DuelLink();window.neonRoom=()=>({code:online?link.code:'',state:mode});link.addEventListener('notice',e=>toast(e.detail));let gameRules=normalizeRules(),remotes=new Map(),hillInfo=null,teamScores=[0,0];
const liveRules=document.createElement('section');liveRules.id='live-rules';liveRules.className='hidden';liveRules.innerHTML='<p class="field-label">HOST CONTROLS · NEXT ROUND</p><div class="room-options"><div><label for="live-mode">GAME MODE</label><select id="live-mode"><option value="duel">1v1 Duel</option><option value="dm">Deathmatch</option><option value="hill">King of the Hill</option><option value="tdm">Team Deathmatch</option></select></div><div><label for="live-map">MAP</label><select id="live-map"><option value="rift">Orbital Rift</option><option value="foundry">Solar Foundry</option><option value="citadel">Eclipse Citadel</option></select></div></div>';$('ready').before(liveRules);
for(const id of ['live-mode','live-map'])$(id).onchange=()=>{if(!isHost||link.locked)return;const next=normalizeRules({mode:$('live-mode').value,map:$('live-map').value,capacity:link.rules.capacity});link.chooseRules(next);};
const hillRing=new T.Mesh(new T.TorusGeometry(3.8,.055,6,80),new T.MeshBasicMaterial({color:0xbbaaee,transparent:true,opacity:.8}));hillRing.rotation.x=Math.PI/2;hillRing.position.y=.08;hillRing.visible=false;scene.add(hillRing);const keys={};let local=makePlayer(0),rival=makePlayer(1),remoteTarget=packetPlayer(rival);
let mode='lobby',online=false,isHost=true,connected=false,ownReady=false,otherReady=false,matchActive=false,matchId='',paused=false,locked=false,pendingLock=false;
let elapsed=0,countdown=0,totalTime=0,last=performance.now(),lastNet=0,lastAuth=0,lastShotRemote=-999,shotSequence=0,receivedShot=-1;
let dragLook=false,mouseFire=false,aim=false,firePress=false,jumpPress=false,slidePress=false,dashPress=false,recoil=0,recoilPitch=0,swayX=0,swayY=0,shotFlash=0,hurt=0,hitFlash=0,announceTime=0,feedTime=0,toastTime=0;
let matchStart=0,lastBotShot=0,botGoal=0,botStrafe=1,botMoveClock=0,botReload=0,footClock=0,frameSum=0,frameCount=0,shotChecks=Array.from({length:8},()=>({last:-10,ammo:[30,8,5],gun:0,reloading:0,seq:-1}));
const ownName=()=>($('nickname').value.trim()||'Ranger').slice(0,16);let rivalName='SENTINEL';
const audio={context:null,master:null,music:null,noise:null,musicTimer:0,musicStep:0};
function initAudio(){try{if(!audio.context){audio.context=new(window.AudioContext||window.webkitAudioContext)();audio.master=audio.context.createGain();audio.master.gain.value=settings.volume;audio.music=audio.context.createGain();audio.music.gain.value=settings.musicVolume*.16;audio.master.connect(audio.context.destination);audio.music.connect(audio.context.destination);const b=audio.context.createBuffer(1,audio.context.sampleRate*.5,audio.context.sampleRate),data=b.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;audio.noise=b;audio.musicTimer=setInterval(musicTick,220);}audio.context.resume().catch(()=>{});}catch{}}
function musicTick(){if(!audio.context||settings.musicVolume<=0||audio.context.state!=='running')return;const c=audio.context,step=audio.musicStep++%16,combat=mode==='match',notes=combat?[55,0,55,65,0,55,73,0,55,0,62,65,0,55,49,0]:[55,0,62,0,65,0,62,0,55,0,48,0,50,0,53,0],n=notes[step];if(!n)return;const osc=c.createOscillator(),gain=c.createGain();osc.type=combat?'sawtooth':'triangle';osc.frequency.value=n;gain.gain.setValueAtTime(.0001,c.currentTime);gain.gain.exponentialRampToValueAtTime((combat?.035:.022)*settings.musicVolume,c.currentTime+.03);gain.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.32);osc.connect(gain);gain.connect(audio.music);osc.start();osc.stop(c.currentTime+.34);}
function sound(kind,volume=1,pan=0){if(!audio.context||settings.volume<=0)return;const c=audio.context,t=c.currentTime,out=c.createGain(),p=c.createStereoPanner();p.pan.value=clamp(pan,-1,1);out.connect(p);p.connect(audio.master);let f=100,end=30,duration=.14,amp=.25,type='sawtooth';if(kind==='shot1'){f=85;duration=.28;amp=.4}else if(kind==='shot2'){f=620;end=60;duration=.4;amp=.22}else if(kind==='hit'){f=1000;end=520;duration=.045;amp=.12;type='sine'}else if(kind==='head'){f=1500;end=700;duration=.12;amp=.16;type='sine'}else if(kind==='hurt'){f=65;duration=.18;amp=.23}else if(kind==='step'){f=120;duration=.035;amp=.025;type='triangle'}else if(kind==='jump'){f=220;end=80;duration=.1;amp=.06;type='triangle'}else if(kind==='reload'){f=280;end=650;duration=.07;amp=.07;type='triangle'}else if(kind==='kill'){f=460;end=1300;duration=.24;amp=.09;type='sine'}else if(kind==='start'){f=440;end=880;duration=.16;amp=.1;type='sine'}
const o=c.createOscillator();o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(end,t+duration);out.gain.setValueAtTime(amp*volume,t);out.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(out);o.start();o.stop(t+duration);if(kind.startsWith('shot')||kind==='hurt'){const n=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();n.buffer=audio.noise;filter.type='lowpass';filter.frequency.value=kind==='shot2'?4200:1700;gain.gain.setValueAtTime(.22*volume,t);gain.gain.exponentialRampToValueAtTime(.001,t+.12);n.connect(filter);filter.connect(gain);gain.connect(p);n.start();n.stop(t+.15)}}
const fx=[];const sparkGeo=new T.IcosahedronGeometry(.025,0),sparkMat=new T.MeshBasicMaterial({color:0xffffff,toneMapped:false});const sparks=new T.InstancedMesh(sparkGeo,sparkMat,180);sparks.instanceMatrix.setUsage(T.DynamicDrawUsage);sparks.count=0;sparks.frustumCulled=false;scene.add(sparks);const particles=[];const matrix=new T.Matrix4(),dummy=new T.Object3D();
function burst(position,color=0xffc58a,count=12){if(settings.effects==='off')return;count=settings.effects==='low'?Math.ceil(count*.35):count;for(let i=0;i<count;i++){if(particles.length>178)particles.shift();particles.push({p:new T.Vector3(position.x,position.y,position.z),v:new T.Vector3((Math.random()-.5)*6,Math.random()*5,(Math.random()-.5)*6),life:.3+Math.random()*.4,max:.7,c:new T.Color(color)});}}
function tracer(a,b,color=0xa6ffe1,rail=false){const start=new T.Vector3(a.x,a.y,a.z),end=new T.Vector3(b.x,b.y,b.z),length=start.distanceTo(end);if(length<.05)return;const mesh=new T.Mesh(new T.CylinderGeometry(rail?.028:.009,rail?.028:.009,length,5),new T.MeshBasicMaterial({color,transparent:true,opacity:rail?.95:.75,toneMapped:false,blending:T.AdditiveBlending,depthWrite:false}));mesh.position.copy(start).add(end).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),end.sub(start).normalize());scene.add(mesh);fx.push({mesh,life:rail?.26:.075,max:rail?.26:.075});}
function explosion(p,color=0xff986b){burst({x:p.x,y:p.y+1,z:p.z},color,45);const m=new T.Mesh(new T.SphereGeometry(.5,16,12),new T.MeshBasicMaterial({color,transparent:true,opacity:.4,wireframe:true,depthWrite:false}));m.position.set(p.x,p.y+1,p.z);scene.add(m);fx.push({mesh:m,life:.45,max:.45,expand:true});}
function updateFX(dt){for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.life-=dt;if(f.life<=0){scene.remove(f.mesh);f.mesh.geometry.dispose();f.mesh.material.dispose();fx.splice(i,1);continue}f.mesh.material.opacity=f.life/f.max*.75;if(f.expand)f.mesh.scale.setScalar(1+(1-f.life/f.max)*4)}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.v.y-=9*dt;p.p.addScaledVector(p.v,dt);if(p.p.y<.03){p.p.y=.03;p.v.y=Math.abs(p.v.y)*.3}if(p.life<=0)particles.splice(i,1)}sparks.count=particles.length;particles.forEach((p,i)=>{dummy.position.copy(p.p);dummy.scale.setScalar(Math.max(.1,p.life/p.max));dummy.updateMatrix();sparks.setMatrixAt(i,dummy.matrix);sparks.setColorAt(i,p.c)});sparks.instanceMatrix.needsUpdate=true;if(sparks.instanceColor)sparks.instanceColor.needsUpdate=true;}
function toast(message){$('toast').textContent=message;$('toast').style.opacity=1;toastTime=4;}
function announce(message,seconds=2){$('announcement').textContent=message;announceTime=seconds;}
function feed(message){$('feed').textContent=message;$('feed').style.opacity=1;feedTime=3.5;}
function status(message,error=false){$('lobby-status').textContent=message;$('lobby-status').classList.toggle('error',error);}
function setButtons(disabled){$('host').disabled=disabled;$('join').disabled=disabled;}
function clearInput(){for(const key in keys)keys[key]=false;mouseFire=false;firePress=false;aim=false;jumpPress=false;slidePress=false;dashPress=false;}
function unlock(){locked=false;pendingLock=false;try{document.exitPointerLock?.()}catch{}}
async function lock(){initAudio();if(activeInput==='ps5'){pendingLock=false;paused=false;hide('pause-screen');renderer.domElement.focus();return;}pendingLock=true;renderer.domElement.focus();try{await renderer.domElement.requestPointerLock();}catch{pendingLock=false;dragLook=true;paused=false;hide('pause-screen');toast('Mouse capture unavailable here. Hold a mouse button and drag to aim, or use arrow keys.');}}
function saveSettings(){try{localStorage.setItem('neon-breach-settings-v2',JSON.stringify(settings));localStorage.setItem('neon-breach-name',ownName())}catch{}window.neonAccount?.saveSettings();}
function applyQuality(){const q=['auto','high','medium','low','potato'].includes(settings.quality)?settings.quality:'auto';const base=q==='high'?1.75:q==='auto'?1.5:q==='medium'?1.25:q==='low'?1:.7;renderScale=Math.min(devicePixelRatio,base)*clamp(settings.renderPercent/100,.5,1.5);renderer.setPixelRatio(renderScale);renderer.shadowMap.enabled=settings.shadowQuality==='on'||settings.shadowQuality!=='off'&&!['low','potato'].includes(q);arena.setQuality(renderer.shadowMap.enabled?(q==='high'?'high':'medium'):'low');bloom.enabled=settings.effects==='full'&&!['low','potato'].includes(q);bloom.strength=q==='high'?.4:.27;composer.setPixelRatio(renderScale);composer.setSize(innerWidth,innerHeight);target.samples=q==='potato'||settings.effects==='off'?0:4;target.dispose();}

function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();view.camera.aspect=camera.aspect;view.camera.updateProjectionMatrix();composer.setSize(innerWidth,innerHeight);}
applyQuality();window.addEventListener('resize',resize);

function resetMatch(){teamScores=[0,0];powerNodes.forEach((n,i)=>Object.assign(n,createPowerNodes()[i]));medalTime=0;rivalPing=0;objectiveNotice=false;statsSaved=false;hide('medal');cells.forEach(c=>c.cool=0);buildPlayers();remoteTarget=packetPlayer(rival);local.score=0;rival.score=0;elapsed=0;shotSequence=0;receivedShot=-1;lastShotRemote=-999;shotChecks=Array.from({length:8},()=>({last:-10,ammo:[30,8,5],gun:0,reloading:0,seq:-1}));recoil=0;recoilPitch=0;hurt=0;countdown=3;matchActive=false;mode='match';paused=false;clearInput();hide('lobby');hide('room-screen');hide('result-screen');hide('pause-screen');show('hud');$('you-name').textContent=ownName();$('rival-name').textContent=rivalName;matchStart=totalTime+3;updateHUD();}
function startMatch(){matchId=crypto.randomUUID();if(online){gameRules=normalizeRules(link.rules);link.begin();}applyMap(gameRules.map);resetMatch();if(online)link.send({t:'start',id:matchId,rules:gameRules,members:link.members});ownReady=false;sound('start');}
function practice(){link.close();connected=false;online=false;isHost=true;gameRules=normalizeRules({map:$('room-map')?.value||'rift'});applyMap(gameRules.map);rivalName='SENTINEL';resetMatch();matchId=crypto.randomUUID();lock();}
function lobby(){link.close();online=false;connected=false;ownReady=false;otherReady=false;mode='lobby';matchActive=false;paused=false;clearInput();unlock();for(const id of ['room-screen','hud','pause-screen','result-screen'])hide(id);show('lobby');rivalModel.root.visible=false;setButtons(false);status('Invite your friends. Team sizes are maximums; uneven teams can start.');}
async function openRoom(host){if(innerWidth<650){toast('Use a desktop browser with a keyboard or controller for the best experience.');}initAudio();saveSettings();setButtons(true);status(host?'Creating your private room…':'Connecting to your friend…');online=true;isHost=host;ownReady=false;otherReady=false;connected=false;
try{const code=await link.open(host,$('room-input').value,ownName(),{mode:$('room-mode').value,capacity:+$('room-capacity').value});if(!online)return;$('room-code').textContent=code;$('room-title').textContent=host?'Room created.':'Joining room…';$('room-kicker').textContent='PRIVATE DUEL · FIRST TO 7';$('room-description').textContent=host?'Send this code or invite link to your friend.':'Making a secure connection to the host.';$('host-name').textContent=host?ownName():'HOST';$('guest-name').textContent=host?'WAITING FOR RIVAL':ownName();$('host-ready').textContent=host?'CONNECTED':'CONNECTING';$('guest-ready').textContent=host?'EMPTY SLOT':'CONNECTING';$('ready').disabled=!connected;$('ready').textContent=connected?'ENTER ARENA ↗':'WAITING FOR RIVAL…';$('room-status').textContent='Keep this tab open while your friend joins.';hide('lobby');show('room-screen');mode='room';renderRoom();if(connected)roomConnected();}catch(e){online=false;setButtons(false);status(e.message,true);}}
function roomConnected(){connected=link.members.length>1;gameRules=normalizeRules(link.rules);if(mode==='room'||mode==='lobby')renderRoom();}
function ready(){if(!link.members.some(m=>m.side===link.side))return;ownReady=true;$('ready').disabled=true;lock();link.ready();}
link.addEventListener('connected',e=>{rivalName=e.detail.name;roomConnected();});
link.addEventListener('roster',()=>{ownReady=!!link.members.find(m=>m.side===link.side)?.ready;connected=link.members.length>1;gameRules=normalizeRules(link.rules);if(mode==='room'||mode==='result'){renderRoom();if(isHost&&ownReady&&canStartRoom(link.members,gameRules))startMatch();}for(const [side,r]of remotes)if(!link.members.some(m=>m.side===side)){r.p.dead=999;r.model.root.visible=false;}});
link.addEventListener('left',()=>{if(mode==='match')toast('Player left. The round continues with the remaining players.');});
link.addEventListener('failure',e=>{const message=e.detail;lobby();status(message,true);toast(message);});

function switchGun(index){if(mode!=='match'||paused||!matchActive)return;if(index===local.gun||index<0||index>2||local.dead>0)return;local.gun=index;local.reload=0;local.shotCd=Math.max(local.shotCd,.22);recoil=.3;sound('reload');if(online)link.send({t:'switch',gun:index,id:matchId});}
function reloadGun(){if(mode!=='match'||paused||!matchActive)return;if(local.dead>0||local.reload>0||local.ammo[local.gun]>=WEAPONS[local.gun].cap)return;local.reload=WEAPONS[local.gun].reload;sound('reload');if(online)link.send({t:'reload',gun:local.gun,id:matchId});}
function seeded(seed){let a=seed|0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function raysFor(shot){const random=seeded(shot.seed),w=WEAPONS[shot.gun],spread=w.spread*(shot.aim?.43:1);return Array.from({length:w.pellets},()=>direction(shot.yaw+(random()-.5)*spread*2,shot.pitch+(random()-.5)*spread*2));}
function visuals(shot,shooter,enemyShot=false){const rays=raysFor(shot),color=WEAPONS[shot.gun].color;const origin={x:shot.x,y:shot.y,z:shot.z};const barrel=enemyShot?origin:{x:origin.x+Math.cos(local.yaw)*.22,y:origin.y-.15,z:origin.z-Math.sin(local.yaw)*.22};for(let i=0;i<rays.length;i++){const dir=rays[i],wall=wallDistance(origin,dir),target=enemyShot?local:rival,hit=nearestPlayer(origin,dir,shooter),h=hit?.h,d=h?Math.min(h.distance,wall):wall;const end={x:origin.x+dir.x*d,y:origin.y+dir.y*d,z:origin.z+dir.z*d};if(i<4||shot.gun!==1)tracer(barrel,end,color,shot.gun===2);if(d<100)burst(end,h?0xffba8c:color,shot.gun===1?3:7);}if(enemyShot){shooter.radarUntil=totalTime+1.4;}if(enemyShot)sound('shot'+shot.gun,.45,clamp((shooter.x-local.x)*.06,-.9,.9));}
function fire(){const w=WEAPONS[local.gun];if(!matchActive||local.dead>0||local.shotCd>0||local.reload>0||paused)return;if(local.ammo[local.gun]<=0){reloadGun();return}const aimPitch=clamp(local.pitch+recoilPitch,-1.45,1.45);local.shotCd=w.rate;local.ammo[local.gun]--;local.shield=0;recoil=1;recoilPitch+=w.recoil*(aim?.55:1);shotFlash=.065;sound('shot'+local.gun);if(activeInput==='ps5'&&settings.rumble)controller.rumble(local.gun===0?.18:.4,local.gun===0?45:110);const shot={t:'shot',id:matchId,seq:++shotSequence,gun:local.gun,x:local.x,y:local.y+local.eye,z:local.z,yaw:local.yaw,pitch:aimPitch,seed:Math.floor(Math.random()*2147483647),aim};visuals(shot,local);if(isHost){local.stats.shots++;resolveShot(shot,local,rival,true);if(online)link.send({t:'hostshot',id:matchId,side:local.side,shot});}else link.send(shot);}
function resolveShot(shot,shooter,unused,fromLocal){
 if(!matchActive||shooter.dead>0)return;const hits=new Map();for(const d of raysFor(shot)){const candidate=nearestPlayer({x:shot.x,y:shot.y,z:shot.z},d,shooter);if(!candidate||candidate.p.shield>0||sameTeam(shooter,candidate.p,gameRules))continue;const entry=hits.get(candidate.p.side)||{p:candidate.p,damage:0,head:false};entry.damage+=WEAPONS[shot.gun].damage*(candidate.h.head?WEAPONS[shot.gun].head:1);entry.head=entry.head||candidate.h.head;hits.set(candidate.p.side,entry);}
 for(const {p:victim,damage:raw,head}of hits.values()){const damage=applyDamage(shooter,victim,raw).amount;if(shooter===local){hitFlash=.15;sound(head?'head':'hit');}if(victim===local){hurt=.85;sound('hurt');}
 if(victim.hp<=0){victim.dead=3;shooter.score++;if(gameRules.mode==='tdm')teamScores[shooter.team]++;const award=awardElimination(shooter,victim,{head,distance:Math.hypot(shooter.x-victim.x,shooter.z-victim.z),airborne:shooter.y>1&&!shooter.grounded});if(shooter===local)showMedal(award);if(online)link.send({t:'medal',id:matchId,side:shooter.side,award});explosion(victim);sound('kill');feed(playerName(shooter.side)+' ELIMINATED '+playerName(victim.side));}
 if(online)link.send({t:'damage',id:matchId,side:victim.side,shooter:shooter.side,hp:victim.hp,dead:victim.dead,head,amount:damage,teamScores,players:allPlayers().map(authorityPlayer)});
 if(gameRules.mode!=='hill'&&(gameRules.mode==='tdm'?teamScores[shooter.team]:shooter.score)>=gameRules.limit){finishMatch(shooter.side);break;}}
}
function finishMatch(winner){if(mode==='result')return;matchActive=false;mode='result';paused=false;clearInput();unlock();hide('pause-screen');hide('hud');show('result-screen');const won=winner===local.side||sameTeam(local,getPlayer(winner),gameRules);if(online&&isHost)link.end();$('result-kicker').textContent=won?'THE RIFT IS YOURS':'RIVAL VICTORY';$('result-title').textContent=won?'Victory.':'Run it back.';$('result-score').innerHTML=(gameRules.mode==='tdm'?teamScores[local.team]:Math.floor(points(local,gameRules)))+' <span>—</span> '+(gameRules.mode==='tdm'?teamScores[1-local.team]:Math.floor(Math.max(0,...allPlayers().filter(p=>p!==local).map(p=>points(p,gameRules)))));renderReport(won);$('result-detail').textContent=MODES[gameRules.mode]+' · Winner: '+(gameRules.mode==='tdm'?TEAM_NAMES[getPlayer(winner)?.team]:playerName(winner))+' · '+Math.floor(elapsed/60)+':'+String(Math.floor(elapsed%60)).padStart(2,'0');$('rematch-status').textContent=online?'Everyone chooses Play again for the next round.':'Switch weapons and try a different route.';$('rematch').disabled=false;ownReady=false;otherReady=false;if(online&&isHost)link.send({t:'end',id:matchId,winner,teamScores,players:allPlayers().map(authorityPlayer),elapsed});}
function rematch(){if(!online){practice();return;}ownReady=true;$('rematch').disabled=true;$('rematch-status').textContent='Waiting for everyone to ready up…';lock();link.ready();}

link.addEventListener('message',e=>{
 const m=e.detail;
 if(m.t==='start'&&!isHost&&typeof m.id==='string'){gameRules=normalizeRules(m.rules);applyMap(gameRules.map);if(Array.isArray(m.members))link.members=m.members;matchId=m.id;resetMatch();return;}
 if(m.id!==matchId)return;if(!isHost&&Array.isArray(m.teamScores)&&m.teamScores.length===2&&m.teamScores.every(n=>Number.isFinite(n)&&n>=0))teamScores=m.teamScores.map(n=>clamp(n,0,1000));
 const source=getPlayer(isHost?(m.from??m.side??rival.side):m.side);
 if(m.t==='state'&&source&&source!==local&&validState(m.p)&&m.p.life===source.life){const r=remotes.get(source.side);if(r)r.target=m.p;if(source===rival)remoteTarget=m.p;if(isHost){Object.assign(source,{x:m.p.x,y:m.p.y,z:m.p.z,yaw:m.p.yaw,pitch:m.p.pitch,gun:m.p.gun,grounded:m.p.grounded!==false,slide:m.p.slide?.3:0,eye:Number.isFinite(m.p.eye)?clamp(m.p.eye,.7,1.7):1.65});link.relayState({...m,side:source.side,p:packetPlayer(source)});}return;}
 if(m.t==='boost'&&isHost&&source&&m.life===source.life&&matchActive){if(activateBoost(source))link.send({t:'boosted',id:matchId,side:source.side,combat:packCombat(source)});return;}
 if(m.t==='boosted'&&!isHost&&source){receiveCombat(source,m.combat);source.dashCd=0;if(source===local){showMedal({medal:'OVERDRIVE',reward:'6s HASTE · DASH REFRESHED'});sound('start');}return;}
 if(m.t==='medal'&&!isHost&&m.side===local.side){if(m.award?.streak===3)local.dashCd=0;showMedal(m.award);return;}
 if(m.t==='power'&&!isHost&&source){const node=powerNodes[m.node];if(!node)return;node.cool=30;node.type=m.next;receiveCombat(source,m.combat);if(m.power==='haste')source.dashCd=0;powerFeedback(source,m.power,node);return;}
 if(isHost&&source&&(m.t==='reload'||m.t==='switch')&&Number.isInteger(m.gun)&&m.gun>=0&&m.gun<=2){const ledger=shotChecks[source.side],now=performance.now()/1000;if(ledger.reloading&&now>=ledger.reloading){ledger.ammo[ledger.gun]=WEAPONS[ledger.gun].cap;ledger.reloading=0;}if(m.t==='switch'){ledger.gun=m.gun;ledger.reloading=0;ledger.readyAfter=now+.18;}else if(ledger.ammo[m.gun]<WEAPONS[m.gun].cap){ledger.gun=m.gun;ledger.reloading=now+WEAPONS[m.gun].reload;}return;}
 if(m.t==='shot'&&isHost&&source){if(!matchActive||source.dead>0)return;const ledger=shotChecks[source.side];if(!Number.isInteger(m.seq)||m.seq<=(ledger.seq??-1)||!Number.isInteger(m.gun)||m.gun<0||m.gun>2||!['x','y','z','yaw','pitch','seed'].every(k=>Number.isFinite(m[k])))return;ledger.seq=m.seq;const weapon=WEAPONS[m.gun];if(Math.hypot(m.x-source.x,m.z-source.z)>2||Math.abs(m.y-(source.y+source.eye))>1.2)return;const now=performance.now()/1000;if(ledger.reloading&&now>=ledger.reloading){ledger.ammo[ledger.gun]=WEAPONS[ledger.gun].cap;ledger.reloading=0;}ledger.credit=Math.min(2,(ledger.credit??2)+(now-(ledger.creditTime??now))/weapon.rate);ledger.creditTime=now;if(ledger.credit<1||ledger.ammo[m.gun]<=0||ledger.reloading>now||m.gun!==ledger.gun||(ledger.readyAfter||0)>now)return;ledger.credit--;ledger.ammo[m.gun]--;source.stats.shots++;source.shield=0;visuals(m,source,true);resolveShot(m,source,local,false);link.send({t:'hostshot',id:matchId,side:source.side,shot:m});return;}
 if(m.t==='hostshot'&&!isHost&&source&&source!==local&&m.shot){visuals(m.shot,source,true);return;}
 if(m.t==='damage'&&!isHost&&source){applyAuthority(m.players);if(source===local){hurt=.9;sound('hurt');}else if(m.shooter===local.side){hitFlash=.15;sound(m.head?'head':'hit');}if(source.dead>0){explosion(source);sound('kill');feed(playerName(m.shooter)+' ELIMINATED '+playerName(source.side));}return;}
 if(m.t==='authority'&&!isHost){if(Array.isArray(m.nodes))m.nodes.forEach((n,i)=>{if(powerNodes[i]&&Number.isFinite(n.cool)&&Number.isInteger(n.type)&&n.type>=0&&n.type<3)Object.assign(powerNodes[i],{cool:Math.max(0,n.cool),type:n.type});});applyAuthority(m.players);if(Number.isFinite(m.elapsed))elapsed=m.elapsed;return;}
 if(m.t==='respawn'&&!isHost&&source){resetLife(source);if(source===local){recoil=0;recoilPitch=0;announce('BACK IN THE FIGHT',1);}else{const r=remotes.get(source.side);if(r)r.target=packetPlayer(source);if(source===rival)remoteTarget=packetPlayer(source);}return;}
 if(m.t==='heal'&&!isHost&&source&&[0,1].includes(m.cell)&&Number.isFinite(m.hp)){cells[m.cell].cool=12;source.hp=clamp(m.hp,0,100);if(source===local){announce('+35 INTEGRITY',1);sound('start');}return;}
 if(m.t==='end'&&!isHost&&getPlayer(m.winner)){applyAuthority(m.players);if(Number.isFinite(m.elapsed))elapsed=m.elapsed;finishMatch(m.winner);return;}
});


function updateBot(dt){const skill={easy:{rate:.85,spread:.14,turn:2},normal:{rate:.45,spread:.055,turn:3.6},hard:{rate:.22,spread:.026,turn:6}}[settings.difficulty]||{rate:.45,spread:.055,turn:3.6};if(rival.energy>=100&&Math.hypot(local.x-rival.x,local.z-rival.z)<20)activateBoost(rival);if(rival.dead>0||!matchActive)return;const distance=Math.hypot(local.x-rival.x,local.z-rival.z);const targetYaw=Math.atan2(-(local.x-rival.x),-(local.z-rival.z));rival.yaw=angleLerp(rival.yaw,targetYaw,1-Math.exp(-skill.turn*dt));rival.pitch=lerp(rival.pitch,Math.atan2(local.y+local.eye-(rival.y+rival.eye),distance),1-Math.exp(-3*dt));botMoveClock-=dt;if(botMoveClock<=0){botMoveClock=2+Math.random()*2;botStrafe*=-1;botGoal=(botGoal+1)%4}
const see=wallDistance({x:rival.x,y:rival.y+rival.eye,z:rival.z},direction(targetYaw,rival.pitch))>distance-.6;
if(!see){const waypoints=[{x:-12,z:-12},{x:-12,z:12},{x:12,z:12},{x:12,z:-12}];let goal=waypoints[botGoal];if(Math.hypot(goal.x-rival.x,goal.z-rival.z)<2)botGoal=(botGoal+1)%4;goal=waypoints[botGoal];rival.yaw=angleLerp(rival.yaw,Math.atan2(-(goal.x-rival.x),-(goal.z-rival.z)),1-Math.exp(-5*dt));}
movePlayer(rival,{forward:see?(distance>15?1:distance<5?-.5:.08):1,strafe:see?botStrafe*.6:0,sprint:!see,jump:Math.random()<dt*.09},dt);
if(see&&distance<35&&totalTime-lastBotShot>skill.rate&&Math.abs(Math.atan2(Math.sin(rival.yaw-targetYaw),Math.cos(rival.yaw-targetYaw)))<.2&&local.dead<=0){lastBotShot=totalTime;rival.shield=0;const shot={gun:0,x:rival.x,y:rival.y+rival.eye,z:rival.z,yaw:targetYaw+(Math.random()-.5)*skill.spread,pitch:rival.pitch+(Math.random()-.5)*skill.spread,seed:Math.floor(Math.random()*1e8),aim:false};rival.stats.shots++;visuals(shot,rival,true);resolveShot(shot,rival,local,false)}
}
function updateHUD(){updateEnhancementHUD();updateMatchboard();$('crosshair').classList.toggle('shotgun',local.gun===1);const spreadPixels=Math.tan(WEAPONS[local.gun].spread*(aim?.43:1))*innerHeight/(2*Math.tan(camera.fov*Math.PI/360));$('crosshair').style.setProperty('--spread-size',Math.max(10,spreadPixels*2)+'px');const w=WEAPONS[local.gun];$('hp').textContent=Math.ceil(local.hp);$('hp-bar').style.width=local.hp+'%';$('hp-bar').style.background=local.hp<30?'#ff9777':'#a1ffe1';$('ammo').textContent=local.ammo[local.gun];$('magazine').textContent='/ '+w.cap;$('gun-name').textContent=w.name;$('reload-label').textContent=local.reload>0?'RELOADING '+Math.ceil(local.reload*10)/10+'s':(activeInput==='ps5'?'□ RELOAD · L2 AIM':'R RELOAD · RMB AIM');$('score-you').textContent=local.score;const leader=allPlayers().filter(p=>p!==local).sort((a,b)=>points(b,gameRules)-points(a,gameRules))[0];$('score-you').textContent=Math.floor(points(local,gameRules));$('score-enemy').textContent=Math.floor(leader?points(leader,gameRules):0);$('rival-name').textContent=leader?playerName(leader.side):'WAITING';if(gameRules.mode==='tdm'){$('you-name').textContent=TEAM_NAMES[local.team];$('rival-name').textContent=TEAM_NAMES[1-local.team];$('score-you').textContent=teamScores[local.team];$('score-enemy').textContent=teamScores[1-local.team];}updateScoreList();$('match-clock').textContent=String(Math.floor(elapsed/60)).padStart(2,'0')+':'+String(Math.floor(elapsed%60)).padStart(2,'0');$('ability').textContent=local.slide>0?'SLIDING':local.slideCd>0?'SLIDE CHARGING':(activeInput==='ps5'?'L3 TOGGLE SPRINT · ○ SLIDE':'SHIFT SPRINT · C SLIDE');$('connection').textContent=online?(link.rtt+' MS · '+(isHost?'HOST':allPlayers().length+' PLAYERS')):'SOLO PRACTICE';document.querySelectorAll('[data-slot]').forEach(el=>el.classList.toggle('selected',+el.dataset.slot===local.gun));$('damage').style.opacity=hurt;$('hitmarker').style.opacity=hitFlash>0?1:0;$('crosshair').style.setProperty('--gap',(aim?4:7)+recoil*9+Math.hypot(local.vx,local.vz)*.2+'px');$('scope').classList.toggle('hidden',!(aim&&local.gun===2&&local.dead<=0));}
function respawns(dt){for(const p of allPlayers()){if(p.dead<=0)continue;p.dead=isHost?p.dead-dt:Math.max(.04,p.dead-dt);if(p.dead<=0&&isHost){resetLife(p);shotChecks[p.side]={last:-10,ammo:[30,8,5],gun:0,reloading:0};if(p===local){recoil=0;recoilPitch=0;announce('BACK IN THE FIGHT',1)}else remoteTarget=packetPlayer(p);if(remotes.has(p.side))remotes.get(p.side).target=packetPlayer(p);if(online)link.send({t:'respawn',id:matchId,side:p.side});}}}
function tick(dt){pollController(dt);totalTime+=dt;medalTime-=dt;rivalPing=Math.max(0,rivalPing-dt);if(medalTime<=0)hide('medal');toastTime-=dt;if(toastTime<=0)$('toast').style.opacity=0;shotFlash=Math.max(0,shotFlash-dt);hitFlash=Math.max(0,hitFlash-dt);hurt=Math.max(0,hurt-dt*1.5);recoil=lerp(recoil,0,1-Math.exp(-13*dt));recoilPitch=lerp(recoilPitch,0,1-Math.exp(-11*dt));swayX=lerp(swayX,0,1-Math.exp(-8*dt));swayY=lerp(swayY,0,1-Math.exp(-8*dt));
if(mode==='match'){
 if(countdown>0){announce(''+Math.max(1,Math.ceil(countdown)),.1);if(countdown<=0){matchActive=true;announce('BREACH',.7);sound('start');}}
 if((!paused||online)&&matchActive){
 const pad=activeInput==='ps5'?padFrame?.actions:null;const input={forward:paused?0:pad?pad.forward:activeInput==='kbm'?(keys.KeyW?1:0)-(keys.KeyS?1:0):0,strafe:paused?0:pad?pad.strafe:activeInput==='kbm'?(keys.KeyD?1:0)-(keys.KeyA?1:0):0,sprint:!paused&&(pad?pad.sprint:activeInput==='kbm'&&(keys.ShiftLeft||keys.ShiftRight)),aim,jump:!paused&&(pad?pad.jump:jumpPress),slide:!paused&&(pad?pad.slide:slidePress),dash:!paused&&(pad?pad.dash:dashPress)};if(!paused&&activeInput==='kbm'){local.yaw+=((keys.ArrowLeft?1:0)-(keys.ArrowRight?1:0))*dt*2;local.pitch=clamp(local.pitch+((keys.ArrowUp?1:0)-(keys.ArrowDown?1:0))*dt*1.4,-1.4,1.4)}
 const wasGrounded=local.grounded,oldPad=local.padCd;movePlayer(local,input,dt);if(local.padCd>oldPad+.5){sound('jump',2);showMedal({medal:'LIFT OFF',reward:'AERIAL ROUTE · KEEP MOVING'});}if(input.jump&&wasGrounded){sound('jump')};if(!wasGrounded&&local.grounded){recoil=.22;sound('step',3)};if(local.grounded&&Math.hypot(local.vx,local.vz)>2&&totalTime-footClock>.37){footClock=totalTime;sound('step')}
 if(!paused&&(pad?(pad.fire&&WEAPONS[local.gun].auto||pad.firePress):(mouseFire&&WEAPONS[local.gun].auto||firePress)))fire();jumpPress=false;slidePress=false;dashPress=false;firePress=false;
 if(!online)updateBot(dt);
 if(online&&totalTime-lastNet>1/30){lastNet=totalTime;if(local.dead<=0)link.state(packetPlayer(local),matchId);}
 
 }
 if(online&&!isHost)for(const r of remotes.values()){const p=r.p,t=r.target;p.x=lerp(p.x,t.x,1-Math.exp(-18*dt));p.y=lerp(p.y,t.y,1-Math.exp(-18*dt));p.z=lerp(p.z,t.z,1-Math.exp(-18*dt));p.yaw=angleLerp(p.yaw,t.yaw,1-Math.exp(-20*dt));p.pitch=lerp(p.pitch,t.pitch,1-Math.exp(-20*dt));p.gun=t.gun;p.slide=t.slide?.3:0;}
 if(local.dead>0)announce('SUIT OFFLINE\nRESPAWN IN '+Math.ceil(local.dead),.2);
 hudClock+=dt;if(hudClock>=.05){hudClock=0;updateHUD();}
}
announceTime-=dt;if(announceTime<=0)$('announcement').textContent='';feedTime-=dt;if(feedTime<=0)$('feed').style.opacity=0;
updateHillVisual();arena.update(totalTime,settings.motion==='reduced');powerVisuals.update(totalTime,powerNodes,settings.motion==='reduced');updateFX(dt);cells.forEach(c=>{c.mesh.visible=c.cool<=0;c.mesh.rotation.y=totalTime;c.mesh.position.y=c.y+.55+Math.sin(totalTime*2)*.06;});
}
function updateCells(dt){cells.forEach((cell,i)=>{cell.cool=Math.max(0,cell.cool-dt);if(!isHost||cell.cool>0)return;for(const p of allPlayers()){if(p.dead<=0&&p.hp<100&&Math.hypot(p.x-cell.x,p.z-cell.z)<1.05&&Math.abs(p.y-cell.y)<.6){p.hp=Math.min(100,p.hp+35);cell.cool=12;burst({x:cell.x,y:cell.y+.6,z:cell.z},0x8dffca,18);if(p===local){announce('+35 INTEGRITY',1);sound('start')}if(online)link.send({t:'heal',id:matchId,side:p.side,hp:p.hp,cell:i});break;}}});}
let lastRivalX=0,lastRivalZ=0,renderRival=null;
function render(dt){
 const inGame=mode==='match'||mode==='result';
 if(inGame){const speed=Math.hypot(local.vx,local.vz),bob=settings.motion!=='reduced'&&local.grounded&&local.dead<=0?Math.sin(local.walk*1.7)*Math.min(.032,speed*.005):0;
 camera.position.set(local.x,local.y+local.eye+bob,local.z);camera.rotation.set(local.pitch+recoilPitch,local.yaw,settings.motion==='reduced'?0:(local.slide>0?-.045:0)+Math.sin(local.walk*.85)*Math.min(.007,speed*.001));
 const targetFov=settings.motion!=='reduced'&&local.dash>0?settings.fov+15:aim&&local.dead<=0?WEAPONS[local.gun].ads:settings.fov+(speed>8?5:0);camera.fov=lerp(camera.fov,targetFov,1-Math.exp(-12*dt));camera.updateProjectionMatrix();
 const rivalSpeed=Math.hypot(rival.x-lastRivalX,rival.z-lastRivalZ)/Math.max(.001,dt);lastRivalX=rival.x;lastRivalZ=rival.z;if(!renderRival||Math.hypot(renderRival.x-rival.x,renderRival.z-rival.z)>6)renderRival={...rival};renderRival={...rival,x:lerp(renderRival.x,rival.x,1-Math.exp(-22*dt)),y:lerp(renderRival.y,rival.y,1-Math.exp(-22*dt)),z:lerp(renderRival.z,rival.z,1-Math.exp(-22*dt)),yaw:angleLerp(renderRival.yaw,rival.yaw,1-Math.exp(-22*dt))};rivalModel.update(renderRival,totalTime,rivalSpeed);if(online&&!remotes.has(rival.side))rivalModel.root.visible=false;rivalModel.shield.visible=rival.dead<=0&&(rival.shield>0||rival.armor>0);rivalModel.shield.material.color.setHex(rival.armor>0?0xbfa1ff:0x8bdcf4);for(const r of remotes.values()){if(r.model===rivalModel)continue;const moving=Math.hypot(r.p.x-(r.lastX??r.p.x),r.p.z-(r.lastZ??r.p.z))/Math.max(dt,.001);r.model.update(r.p,totalTime,moving);r.lastX=r.p.x;r.lastZ=r.p.z;r.model.shield.visible=r.p.dead<=0&&(r.p.armor>0||r.p.shield>0);}
 }else{const a=.34+Math.sin(totalTime*.065)*.08;camera.position.set(17*Math.sin(a)+5,5.6,16.5);camera.lookAt(-1.3,2,0);camera.fov=66;camera.updateProjectionMatrix();rivalModel.root.visible=false;for(const r of remotes.values())r.model.root.visible=false;}
 renderer.autoClear=true;if(bloom.enabled)composer.render(dt);else renderer.render(scene,camera);
 if(mode==='match'&&local.dead<=0){const w=WEAPONS[local.gun],reloadProgress=local.reload>0?1-local.reload/w.reload:0,reloadDip=local.reload>0?Math.sin(reloadProgress*Math.PI):0;view.guns.forEach((g,i)=>{g.group.visible=i===local.gun&&!(aim&&i===2);g.flash.visible=i===local.gun&&shotFlash>0&&!aim;g.flash.rotation.z=Math.random()*6;g.lamp.intensity=shotFlash>0?3:0;});const gun=view.guns[local.gun].group;const ads=aim?1:0;
 gun.position.x=lerp(gun.position.x,ads?.08:.29,1-Math.exp(-16*dt));gun.position.y=lerp(gun.position.y,ads?-.25:-.28,1-Math.exp(-16*dt));view.rig.position.set(settings.motion==='reduced'?0:Math.sin(local.walk*1.3)*.007+swayX,(settings.motion==='reduced'?0:Math.abs(Math.cos(local.walk*1.3))*.006-swayY)-reloadDip*.22,recoil*(ads?.018:.065));view.rig.rotation.set(recoil*(ads?.018:.11)-reloadDip*.35,-reloadDip*.4,-reloadDip*.6+(local.slide>0?.18:0)+swayX*2);
 renderer.autoClear=false;renderer.clearDepth();renderer.render(view.scene,view.camera);renderer.autoClear=true;}
}
let perfWindow=0,capLast=performance.now(),capBudget=0;function frame(now){capBudget+=now-capLast;capLast=now;const cap=document.hidden?15:+settings.frameLimit;if(cap&&capBudget<1000/cap){requestAnimationFrame(frame);return;}if(cap)capBudget%=1000/cap;else capBudget=0;const rawDt=Math.max(.0001,(now-last)/1000),dt=Math.min(.045,rawDt);last=now;tick(dt);render(dt);frameSum+=rawDt;perfSeconds+=rawDt;perfFrames++;if(perfSeconds>=3){const fps=perfFrames/perfSeconds;if(settings.quality==='auto'&&rawDt<.15&&!document.hidden){const next=clamp(renderScale+(fps<Math.min(+settings.frameLimit||60,60)*.8?-.12:fps>Math.min(+settings.frameLimit||60,60)*.96?.05:0),.5,Math.min(devicePixelRatio,1.5)*settings.renderPercent/100);if(Math.abs(next-renderScale)>.01){renderScale=next;renderer.setPixelRatio(next);composer.setPixelRatio(next);}}perfSeconds=0;perfFrames=0;}frameCount++;if(frameSum>=1){$('fps').textContent=Math.round(frameCount/frameSum)+' FPS';frameSum=0;frameCount=0;}requestAnimationFrame(frame);}

function pause(){if(mode!=='match'||paused)return;paused=true;clearInput();unlock();$('pause-note').textContent=online?'The match keeps running while this menu is open.':'Your practice is paused.';show('pause-screen');}
function resume(){hide('pause-screen');paused=false;lock();}
document.addEventListener('keydown',e=>{if(e.target.matches('input,select')||$('settings').open||$('guide').open)return;if(mode==='match'&&['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab','ControlLeft','ControlRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&mode==='match'){e.preventDefault();paused?resume():pause();return;}if(e.code==='Tab'&&mode==='match'){keys.Tab=true;updateMatchboard();return;}if(!claimKeyboardMouse())return;keys[e.code]=true;if(e.repeat)return;if(e.code==='Escape'&&mode==='match')pause();if(e.code==='Space')jumpPress=true;if(e.code==='KeyQ')dashPress=true;if(e.code==='KeyE')useBoost();if(e.code==='KeyC'||e.code.startsWith('Control'))slidePress=true;if(e.code==='KeyR')reloadGun();if(['Digit1','Digit2','Digit3'].includes(e.code))switchGun(+e.code.slice(-1)-1);if(e.code==='KeyF'){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>toast('Fullscreen is unavailable in this preview.'));else document.exitFullscreen?.();}});
document.addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='Tab')updateMatchboard();});document.addEventListener('mousemove',e=>{if((!locked&&!(dragLook&&(mouseFire||aim)))||paused||mode!=='match')return;if(Math.abs(e.movementX)+Math.abs(e.movementY)>1&&!claimKeyboardMouse())return;const scale=.0017*settings.sensitivity*(aim?.65:1);local.yaw-=e.movementX*scale;local.pitch=clamp(local.pitch-e.movementY*scale,-1.42,1.42);swayX=clamp(swayX-e.movementX*.000055,-.022,.022);swayY=clamp(swayY-e.movementY*.00005,-.02,.02)});
renderer.domElement.addEventListener('mousedown',e=>{if(mode!=='match'||paused||!claimKeyboardMouse())return;if(!locked&&!dragLook){lock();return}if(e.button===0){mouseFire=true;firePress=true}if(e.button===2)aim=true});document.addEventListener('mouseup',e=>{if(e.button===0)mouseFire=false;if(e.button===2&&activeInput==='kbm')aim=false});document.addEventListener('contextmenu',e=>{if(mode==='match')e.preventDefault()});
document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===renderer.domElement;if(locked){pendingLock=false;if(mode==='match'){paused=false;hide('pause-screen');}}else if(mode==='match'&&!paused&&!pendingLock&&!dragLook&&activeInput==='kbm')pause();});window.addEventListener('blur',()=>{if(mode==='match')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='match')pause();});
renderer.domElement.addEventListener('wheel',e=>{if(mode==='match'&&!paused&&claimKeyboardMouse()){e.preventDefault();switchGun((local.gun+(e.deltaY>0?1:2))%3)}},{passive:false});
$('practice').onclick=practice;$('host').onclick=()=>openRoom(true);$('join').onclick=()=>openRoom(false);$('ready').onclick=ready;$('leave-room').onclick=lobby;$('resume').onclick=resume;$('quit').onclick=lobby;$('result-quit').onclick=lobby;$('rematch').onclick=rematch;
$('room-input').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();openRoom(false)}});
$('copy-invite').onclick=async()=>{const u=new URL(location.href);u.hash='room='+link.code;try{await navigator.clipboard.writeText(u.href);toast('Invite link copied. Send it to your friend.')}catch{toast('Copy this room code: '+link.code)}};
function openSettings(){if(mode==='match')pause();$('settings').showModal();}$('settings-open').onclick=openSettings;$('pause-settings').onclick=openSettings;
for(const id of ['sensitivity','fov','volume','music-volume']){$(id).value=id==='volume'?settings.volume*100:id==='music-volume'?settings.musicVolume*100:settings[id];$(id).oninput=()=>{if(id==='volume')settings.volume=+$(id).value/100;else if(id==='music-volume')settings.musicVolume=+$(id).value/100;else settings[id]=+$(id).value;$(id+'-value').textContent=(id==='volume'||id==='music-volume')?$(id).value+'%':id==='sensitivity'?(+$(id).value).toFixed(1):$(id).value;if(audio.master)audio.master.gain.value=settings.volume;if(audio.music)audio.music.gain.value=settings.musicVolume*.16;saveSettings();};$(id).oninput();}
setupPerformanceSettings();setupControllerSettings();setupEnhancementSettings();$('quality').value=settings.quality;$('quality').onchange=()=>{settings.quality=$('quality').value;applyQuality();saveSettings();};
window.addEventListener('pagehide',()=>link.close());
const roomHash=new URLSearchParams(location.hash.slice(1)).get('room');if(roomHash){$('room-input').value=roomHash.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,8);status('Your friend invited you. Choose a callsign and hit JOIN.');}
let clockLast=Date.now();const gameClock=new Worker('./match-clock.js');gameClock.onmessage=()=>{const now=Date.now(),dt=Math.min(20,(now-clockLast)/1000);clockLast=now;if(mode!=='match'||(paused&&!online))return;if(countdown>0){countdown-=dt;if(countdown<=0){countdown=0;matchActive=true;announce('BREACH',.7);sound('start');}}else if(matchActive){elapsed+=dt;respawns(dt);updateCells(dt);updatePowerRules(dt);if(isHost)for(const p of allPlayers())if(p!==local)p.shield=Math.max(0,p.shield-dt);if(isHost&&gameRules.mode==='hill'){hillInfo=tickHill(elapsed,dt,allPlayers());const winner=allPlayers().find(p=>points(p,gameRules)>=gameRules.limit);if(winner)finishMatch(winner.side);}if(online&&isHost)link.send({t:'authority',id:matchId,players:allPlayers().map(authorityPlayer),teamScores,elapsed,nodes:powerNodes.map(n=>({cool:n.cool,type:n.type}))});}};hide('loading');show('lobby');requestAnimationFrame(frame);
// Read-only diagnostics used by the included local verification tooling.
window.neonDebug={get state(){return {mode,online,isHost,connected,ownReady,otherReady,matchActive,matchId,paused,locked,local:{...local},rival:{...rival},renderer:renderer.info.render,network:{rtt:link.rtt,open:link.conn?.open,channel:link.stateChannel?.readyState}};}};

function showMedal(award){if(!award)return;$('medal-title').textContent=award.medal||'POWER ONLINE';$('medal-detail').textContent=award.reward||(award.streak>1?award.streak+' KILL STREAK':'KEEP THE MOMENTUM');show('medal');medalTime=3;}
function useBoost(){if(mode!=='match'||paused||!matchActive||local.dead>0)return;if(local.boost>0){toast('Haste is already active. Save your charge.');return;}if(local.energy<99.99){toast('Overdrive charging · '+Math.floor(local.energy)+'%');return;}if(isHost){if(activateBoost(local)){showMedal({medal:'OVERDRIVE',reward:'6s HASTE · DASH REFRESHED'});sound('start');if(online)link.send({t:'boosted',id:matchId,side:local.side,combat:packCombat(local)});}}else link.send({t:'boost',id:matchId,life:local.life});}
function powerFeedback(p,type,node){burst({x:node.x,y:1,z:node.z},type==='surge'?0xffb264:type==='armor'?0xc6a0ff:0x80ffdd,22);if(p===local){showMedal({medal:'POWER ACQUIRED',reward:POWER_NAMES[type]});sound('start');}else feed(playerName(p.side)+' CLAIMED '+POWER_NAMES[type]);}
function updatePowerRules(dt){
 if(!isHost){for(const n of powerNodes)n.cool=Math.max(0,n.cool-dt);return;}
 for(const p of allPlayers())tickPowers(p,dt);
 powerNodes.forEach((n,i)=>{const before=n.cool;n.cool=Math.max(0,n.cool-dt);if(before>0&&n.cool===0){sound('start',.5);feed('POWER DROP ONLINE · CHECK YOUR MAP');}if(n.cool>0)return;
 // Alternate tie priority by node so neither spawn has both pickups in a simultaneous contest.
 const players=allPlayers().sort((a,b)=>((a.side+i)%2)-((b.side+i)%2));
 for(const p of players){if(p.dead>0||Math.abs(p.y-n.y)>.6||Math.hypot(p.x-n.x,p.z-n.z)>1.1)continue;const type=POWER_TYPES[n.type];grantPower(p,type);n.cool=30;n.type=(n.type+1)%3;powerFeedback(p,type,n);if(online)link.send({t:'power',id:matchId,node:i,side:p.side,power:type,next:n.type,combat:packCombat(p)});break;}
 });
}
function updateEnhancementHUD(){
 $('armor').textContent=Math.ceil(local.armor);$('armor-label').style.visibility=local.armor>0?'visible':'hidden';$('boost-charge').textContent=local.boost>0?Math.ceil(local.boost)+'s':Math.floor(local.energy)+'%';$('boost-label').textContent=local.boost>0?'HASTE ACTIVE':local.energy>=99.99?(activeInput==='ps5'?'R1 · ACTIVATE OVERDRIVE':'E · ACTIVATE OVERDRIVE'):(activeInput==='ps5'?'R1 · OVERDRIVE':'E · OVERDRIVE');$('boost-bar').style.width=(local.boost>0?Math.min(100,local.boost/12*100):local.energy)+'%';$('boost-label').parentElement.classList.toggle('ready',local.energy>=99.99&&local.boost<=0);document.querySelectorAll('[data-streak]').forEach(el=>el.classList.toggle('earned',local.streak>=+el.dataset.streak));
 const effects=[];if(local.surge>0)effects.push('SURGE · +25% DAMAGE · '+Math.ceil(local.surge)+'s');if(local.boost>0)effects.push('HASTE · +22% SPEED · '+Math.ceil(local.boost)+'s');const dashKey=activeInput==='ps5'?'L1':'Q';effects.push(local.dashCd>0?dashKey+' DASH · '+local.dashCd.toFixed(1)+'s':dashKey+' DASH · READY');$('power-status').replaceChildren(...effects.map(s=>{const el=document.createElement('span');el.textContent=s;return el;}));$('boost-vignette').style.opacity=local.boost>0&&local.dead<=0?1:0;
 const available=powerNodes.filter(n=>n.cool<=0);$('objective').textContent=available.length?available.length+' POWER DROP'+(available.length>1?'S':'')+' ONLINE':'NEXT DROP · '+Math.ceil(Math.min(...powerNodes.map(n=>n.cool)))+'s';drawRadar();
}
function drawRadar(){
 const g=radar,w=176,h=146,s=3.12,x=v=>w/2+v*s,y=v=>h/2+v*s;g.clearRect(0,0,w,h);g.fillStyle='#0b1d28';g.fillRect(x(-24),y(-19),48*s,38*s);g.strokeStyle='#466375';g.strokeRect(x(-24),y(-19),48*s,38*s);g.fillStyle='#355162';for(const b of BLOCKS)g.fillRect(x(b.x-b.w/2),y(b.z-b.d/2),b.w*s,b.d*s);for(const p of JUMP_PADS){g.fillStyle='#78caff';g.fillRect(x(p.x)-2,y(p.z)-2,4,4);}for(const c of cells){g.fillStyle=c.cool>0?'#39554c':'#8dffca';g.fillRect(x(c.x)-2,y(c.z)-2,4,4);}for(const n of powerNodes){g.strokeStyle=['#c6a0ff','#80ffdd','#ffb264'][n.type];g.globalAlpha=n.cool>0?.3:1;g.beginPath();g.arc(x(n.x),y(n.z),4,0,Math.PI*2);g.stroke();}g.globalAlpha=1;for(const p of allPlayers()){if(p!==local&&(sameTeam(local,p,gameRules)||p.radarUntil>totalTime)&&p.dead<=0){g.fillStyle=sameTeam(local,p,gameRules)?'#80ffdd':'#ff9961';g.beginPath();g.arc(x(p.x),y(p.z),3,0,Math.PI*2);g.fill();}}if(gameRules.mode==='hill'){hillInfo=hillState(elapsed,allPlayers());g.strokeStyle='#80ffdd';g.beginPath();g.arc(x(hillInfo.center.x),y(hillInfo.center.z),3.8*s,0,Math.PI*2);g.stroke();}g.save();g.translate(x(local.x),y(local.z));g.rotate(-local.yaw);g.fillStyle='#effff6';g.beginPath();g.moveTo(0,-5);g.lineTo(3.5,4);g.lineTo(0,2);g.lineTo(-3.5,4);g.closePath();g.fill();g.restore();
}
function renderReport(won){
 const stats=[['ACCURACY',accuracy(local)+'%'],['DAMAGE',Math.round(local.stats.damage)],['BEST STREAK',local.stats.best],['HEADSHOT KILLS',local.stats.headshots]];$('match-report').replaceChildren(...stats.map(([label,value])=>{const box=document.createElement('div'),n=document.createElement('strong'),l=document.createElement('small');n.textContent=value;l.textContent=label;box.append(n,l);return box;}));
 if(statsSaved)return;statsSaved=true;try{const key=online?'neon-career-duel':'neon-career-practice',stored=window.neonAccount?.profile?.stats||JSON.parse(localStorage.getItem(key)||'{}'),career={matches:(+stored.matches||0)+1,wins:(+stored.wins||0)+(won?1:0),kills:(+stored.kills||0)+local.score,best:Math.max(+stored.best||0,local.stats.best)};localStorage.setItem(key,JSON.stringify(career));window.neonAccount?.saveStats(career);$('career-note').textContent=(online?'DUEL':'PRACTICE')+' CAREER · '+career.wins+'/'+career.matches+' WINS · '+career.kills+' ELIMINATIONS · BEST STREAK '+career.best;}catch{$('career-note').textContent='Career storage unavailable in this browser.';}
}
function setupEnhancementSettings(){
 const values={atmosphere:['aurora','solar','eclipse'],reticle:['mint','white','pink','gold'],motion:['full','reduced'],difficulty:['easy','normal','hard']};for(const [id,allowed]of Object.entries(values)){if(!allowed.includes(settings[id]))settings[id]=allowed[0];$(id).value=settings[id];$(id).onchange=()=>{settings[id]=$(id).value;applyEnhancementSettings();saveSettings();};}applyEnhancementSettings();$('guide-open').onclick=()=>{$('guide').showModal();};
}
function applyEnhancementSettings(){arena.setAtmosphere(settings.atmosphere);document.documentElement.style.setProperty('--reticle',{mint:'#a1ffe1',white:'#ffffff',pink:'#ff72cf',gold:'#ffe278'}[settings.reticle]);}

function setInputDevice(device){if(device===activeInput)return;activeInput=device;clearInput();if(device==='ps5')unlock();updateInputPrompts();}
function claimKeyboardMouse(){if(settings.inputMode==='ps5')return false;if(settings.inputMode==='auto')setInputDevice('kbm');return true;}
function updateInputPrompts(){const ps=activeInput==='ps5';document.body.classList.toggle('ps5-input',ps);$('input-badge').textContent=ps?'PS5 CONTROLLER':'KEYBOARD / MOUSE';$('input-help').textContent=ps?'✕ JUMP   ○ SLIDE   □ RELOAD   △ SWITCH   L2 AIM   R2 FIRE':'WASD MOVE · SPACE JUMP · R RELOAD · MOUSE AIM / FIRE';document.querySelectorAll('[data-slot] b').forEach(el=>el.textContent=ps?'△':String(+el.parentElement.dataset.slot+1));}
function setupControllerSettings(){if(!['auto','kbm','ps5'].includes(settings.inputMode))settings.inputMode='auto';settings.padSensitivity=clamp(+settings.padSensitivity||1.2,.4,3);settings.deadzone=clamp(+settings.deadzone||.14,.05,.3);$('input-mode').value=settings.inputMode;$('input-mode').onchange=()=>{settings.inputMode=$('input-mode').value;controller.reset();setInputDevice(settings.inputMode==='ps5'?'ps5':'kbm');saveSettings();updateInputPrompts();};for(const [id,key]of[['pad-sensitivity','padSensitivity'],['pad-deadzone','deadzone']]){$(id).value=settings[key];$(id).oninput=()=>{settings[key]=+$(id).value;$(id+'-value').textContent=key==='deadzone'?Math.round(settings[key]*100)+'%':settings[key].toFixed(1);saveSettings();};$(id).oninput();}updateInputPrompts();}
function pollController(dt){
 const context=mode+'|'+paused+'|'+local.life+'|'+$('settings').open+'|'+$('guide').open;if(context!==padContext){controller.reset();padContext=context;}
 padFrame=controller.poll(settings.deadzone);if(padFrame.disconnected&&activeInput==='ps5'){clearInput();pause();toast('Controller disconnected. Reconnect and resume, or choose Keyboard & Mouse in Settings.');if(settings.inputMode==='auto')setInputDevice('kbm');}
 if(document.hidden){controller.reset();padFrame.actions=null;return;}
 if(settings.inputMode==='auto'&&padFrame.activity)setInputDevice('ps5');
 padUiClock+=dt;if(padUiClock>.25){padUiClock=0;const text=controller.error||(padFrame.unsupported?'Unmapped controller. Try USB with desktop Chrome or Edge.':padFrame.connected?'Controller connected · '+(padFrame.armed?'ready':'release buttons to start'):'Connect via USB or Bluetooth, then press a controller button.');if(text!==padStatus){padStatus=text;$('controller-status').textContent=text;}}
 if(activeInput!=='ps5'||!padFrame.actions)return;const a=padFrame.actions;
 if($('settings').open||$('guide').open||mode!=='match'||paused){controllerMenu(a,dt);return;}
 if(a.menu){pause();return;}if(!matchActive||local.dead>0)return;aim=a.aim;const scale=settings.padSensitivity*2.4*(aim?.45:1);local.yaw-=a.lookX*scale*dt;local.pitch=clamp(local.pitch-a.lookY*scale*.75*dt,-1.42,1.42);if(a.reload)reloadGun();if(a.next)switchGun((local.gun+1)%3);if(a.boost)useBoost();
}
function controllerMenu(a,dt){
 const dialog=$('settings').open?$('settings'):$('guide').open?$('guide'):null;
 if(a.back||a.menu){if(dialog)dialog.close();else if(mode==='match'&&paused)resume();else if(mode==='room'&&a.back)lobby();return;}
 const container=dialog||(paused?$('pause-screen'):mode==='room'?$('room-screen'):mode==='result'?$('result-screen'):$('lobby'));
 const elements=[...container.querySelectorAll('button,input,select')].filter(el=>!el.disabled&&el.getClientRects().length);if(!elements.length)return;const buttons=padFrame.sample.buttons;const direction=buttons[12]||a.forward>.55?-1:buttons[13]||a.forward<-.55?1:0;menuRepeat-=dt;
 if(direction&&(menuDirection!==direction||menuRepeat<=0)){let i=elements.indexOf(document.activeElement);elements[(i+direction+elements.length)%elements.length].focus();document.activeElement.scrollIntoView({block:'nearest'});menuRepeat=menuDirection===direction?.18:.4;}menuDirection=direction;
 const focused=elements.includes(document.activeElement)?document.activeElement:elements[0];const left=padFrame.pressed[14],right=padFrame.pressed[15],step=right?1:left?-1:0;
 if(step){if(focused.tagName==='SELECT'){const options=[...focused.options].filter(o=>!o.hidden&&!o.disabled),current=options.indexOf(focused.selectedOptions[0]);focused.value=options[clamp(current+step,0,options.length-1)]?.value||focused.value;focused.dispatchEvent(new Event('change',{bubbles:true}));}else if(focused.type==='range'){focused.value=clamp(+focused.value+step*(+focused.step||1),+focused.min,+focused.max);focused.dispatchEvent(new Event('input',{bubbles:true}));}}
 if(a.accept){if(focused.tagName==='BUTTON')focused.click();else{focused.focus();if(focused.type==='text')toast('Use the keyboard to enter your name or room code.');}}
}

function allPlayers(){if(!online)return [local,rival];const present=new Set(link.members.map(m=>m.side));return [local,...[...remotes.values()].map(r=>r.p)].filter(p=>present.has(p.side));}
function getPlayer(side){return side===local.side?local:remotes.get(side)?.p||(!online&&side===rival.side?rival:null);}
function playerName(side){return side===local.side?ownName():online?(link.members.find(m=>m.side===side)?.name||'Player'):'SENTINEL';}
function makeMatchPlayer(side){const member=link.members.find(m=>m.side===side);if(!online||gameRules.mode!=='tdm')return makePlayer(side);const team=member?.team??0,slot=link.members.filter(m=>m.team===team).findIndex(m=>m.side===side),p=makePlayer(side,Math.max(0,slot)*2+team);p.team=team;return p;}
function buildPlayers(){for(const r of remotes.values())if(r.model!==rivalModel){scene.remove(r.model.root);r.model.root.traverse(o=>{if(o.isMesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});}remotes.clear();local=makeMatchPlayer(online?link.side:0);const members=online?link.members.filter(m=>m.side!==local.side):[{side:1}];members.forEach((m,i)=>{const p=makeMatchPlayer(m.side),model=i===0?rivalModel:makeSoldier([0xff9b70,0xb5a0ff,0xffd179,0x91ccff][m.side%4]);model.setSkin(m.skin||'mint');model.setColor(gameRules.mode==='tdm'?(p.team===0?0x80ffdd:0xffb264):[0xff9b70,0xb5a0ff,0xffd179,0x91ccff][m.side%4]);if(i>0)scene.add(model.root);remotes.set(m.side,{p,model,target:packetPlayer(p)});});rival=[...remotes.values()][0]?.p||makePlayer(1);renderRival=null;rivalName=playerName(rival.side);}
function authorityPlayer(p){return {side:p.side,hp:p.hp,score:p.score,hill:p.hill||0,dead:p.dead,shield:p.shield,...packCombat(p)};}
function applyAuthority(players){if(!Array.isArray(players)||players.length>8)return;for(const data of players){const p=getPlayer(data.side);if(!p||!Number.isFinite(data.hp)||!Number.isFinite(data.score))continue;p.hp=clamp(data.hp,0,100);p.score=clamp(data.score,0,1000);p.hill=clamp(data.hill||0,0,1000);p.dead=Math.max(0,data.dead||0);p.shield=Math.max(0,data.shield||0);receiveCombat(p,data);}}
function nearestPlayer(origin,dir,shooter){let nearest=null;for(const p of allPlayers()){if(p===shooter)continue;const h=hitPlayer(origin,dir,p);if(h&&(!nearest||h.distance<nearest.h.distance))nearest={p,h};}return nearest;}
function renderRoom(){
 if(mode==='room')$('ready').before($('live-rules'));const rules=normalizeRules(link.rules),team=rules.mode==='tdm',mine=link.members.find(m=>m.side===link.side),counts=teamCounts(link.members);
 $('room-kicker').textContent=MODES[rules.mode].toUpperCase()+' · '+(team?counts.join('v')+' / '+rules.capacity/2+'v'+rules.capacity/2+' MAX':link.members.length+'/'+rules.capacity+' PLAYERS MAX');
 $('room-title').textContent=connected?'Squad assembled.':isHost?'Room created.':'Connecting to host…';
 $('room-description').textContent=!mine?'Establishing the player connection. Keep both games open.':'Start with whoever is here. Empty slots and uneven teams are allowed.';
 $('room-roster').replaceChildren(...link.members.map(m=>{const row=document.createElement('div'),name=document.createElement('strong'),state=document.createElement('small');row.className=team?(m.team===0?'cyan-team':'amber-team'):'';name.textContent=(team?TEAM_NAMES[m.team]+' · ':'')+m.name+(m.side===0?' · HOST':'');state.textContent=m.ready?'READY':'CONNECTED';row.append(name,state);return row;}));
 $('team-choice').classList.toggle('hidden',!team||!mine);[0,1].forEach(t=>{const button=$(t===0?'team-cyan':'team-amber');button.textContent=TEAM_NAMES[t]+' · '+counts[t]+'/'+rules.capacity/2+(mine?.team===t?' · YOUR TEAM':'');button.disabled=!mine||link.locked||!canJoinTeam(link.members,link.side,t,rules);button.setAttribute('aria-pressed',String(mine?.team===t));});
 $('live-rules').classList.toggle('hidden',!isHost||link.locked);$('live-mode').value=rules.mode;$('live-map').value=rules.map;
 $('ready').disabled=!mine||ownReady;$('ready').textContent=!mine?'CONNECTING…':ownReady?'READY · WAITING FOR OTHERS':isHost?'START WITH CURRENT PLAYERS ↗':'READY UP ↗';
 $('room-status').textContent=(rules.mode==='hill'?'Hold an uncontested hill for 60 seconds to win.':team?'First team to 30 eliminations. Friendly fire off.':'First to '+rules.limit+' eliminations wins.')+' All present players must be ready. No minimum team size. Join between rounds.';
 if(mode==='result'){$('result-screen').append($('live-rules'));$('rematch-status').textContent=link.members.filter(m=>m.ready).length+'/'+link.members.length+' READY · Everyone chooses Play again.';$('rematch').disabled=ownReady;}
}

function updateScoreList(){const list=allPlayers().slice().sort((a,b)=>points(b,gameRules)-points(a,gameRules));$('match-rule').textContent=gameRules.mode==='hill'?'HILL · FIRST TO 60s':MODES[gameRules.mode].toUpperCase()+' · '+gameRules.limit;$('score-list').classList.toggle('hidden',!online||gameRules.mode==='duel');const key=list.map(p=>p.side+':'+Math.floor(points(p,gameRules))+':'+p.stats.deaths).join('|');if($('score-list').dataset.key!==key){$('score-list').dataset.key=key;$('score-list').replaceChildren(...list.map(p=>{const row=document.createElement('div');row.className=p===local?'me':'';const name=document.createElement('span'),score=document.createElement('b');name.textContent=(gameRules.mode==='tdm'?TEAM_NAMES[p.team]+' · ':'')+playerName(p.side);score.textContent=Math.floor(points(p,gameRules))+(gameRules.mode==='hill'?'s':'');row.append(name,score);return row;}));}const h=gameRules.mode==='hill'?hillState(elapsed,list):null;$('hill-status').textContent=h?(h.contested?'CONTESTED':h.owner===null?'CAPTURE THE HILL':playerName(h.owner)+' CONTROLS')+' · ROTATES IN '+Math.ceil(h.remaining)+'s':'';}
function updateHillVisual(){hillRing.visible=mode==='match'&&gameRules.mode==='hill';if(!hillRing.visible)return;const h=hillState(elapsed,allPlayers());hillRing.position.set(h.center.x,.08,h.center.z);hillRing.material.color.setHex(h.contested?0xffeecc:h.owner===local.side?0x8dffd9:h.owner!==null?0xff986a:0xc7a6ff);hillRing.material.opacity=.65+Math.sin(totalTime*3)*.15;}

function setupPerformanceSettings(){settings.renderPercent=clamp(+settings.renderPercent||100,50,150);for(const [id,key,values]of[['shadow-quality','shadowQuality',['auto','on','off']],['effect-quality','effects',['full','low','off']],['frame-limit','frameLimit',['0','30','60','120','144']]]){if(!values.includes(String(settings[key])))settings[key]=values[0];$(id).value=settings[key];$(id).onchange=()=>{settings[key]=$(id).value;applyQuality();saveSettings();};}$('render-scale').value=settings.renderPercent;$('render-scale-value').textContent=settings.renderPercent+'%';$('render-scale').oninput=()=>{settings.renderPercent=+$('render-scale').value;$('render-scale-value').textContent=settings.renderPercent+'%';applyQuality();saveSettings();};$('team-cyan').onclick=()=>link.chooseTeam(0);$('team-amber').onclick=()=>link.chooseTeam(1);$('room-mode').onchange=()=>{const team=$('room-mode').value==='tdm';for(const option of $('room-capacity').options){const n=+option.value;option.textContent=team?(n/2)+'v'+(n/2)+' maximum':n+' players maximum';}const duel=$('room-mode').value==='duel';$('room-capacity').disabled=duel;if(duel)$('room-capacity').value='2';else if($('room-capacity').value==='2')$('room-capacity').value='4';$('room-capacity').querySelector('[value="2"]').hidden=!duel;};$('room-mode').onchange();applyQuality();}

function updateMatchboard(){const visible=mode==='match'&&!!keys.Tab;$('matchboard').classList.toggle('hidden',!visible);if(!visible)return;const rows=allPlayers().slice().sort((a,b)=>points(b,gameRules)-points(a,gameRules));$('matchboard-rows').replaceChildren(...rows.map(p=>{const row=document.createElement('tr');for(const value of [playerName(p.side),gameRules.mode==='tdm'?TEAM_NAMES[p.team]:'—',p.score,p.stats.deaths,Math.floor(points(p,gameRules)),p===local&&online?link.rtt+' ms':'—']){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}return row;}));}

function syncCloudSettings(){for(const [id,key,mult]of[['sensitivity','sensitivity',1],['fov','fov',1],['volume','volume',100],['music-volume','musicVolume',100],['render-scale','renderPercent',1]]){if($(id)){$(id).value=settings[key]*mult;if($(id+'-value'))$(id+'-value').textContent=settings[key]*mult+(mult===100||id==='render-scale'?'%':'');}}for(const [id,key]of[['quality','quality'],['shadow-quality','shadowQuality'],['effect-quality','effects'],['frame-limit','frameLimit'],['input-mode','inputMode'],['atmosphere','atmosphere'],['reticle-color','reticle'],['camera-motion','motion'],['bot-difficulty','difficulty']])if($(id))$(id).value=settings[key];applyQuality();arena.setAtmosphere(settings.atmosphere);if(audio.master)audio.master.gain.value=settings.volume;if(audio.music)audio.music.gain.value=settings.musicVolume*.16;try{localStorage.setItem('neon-breach-settings-v2',JSON.stringify(settings));}catch{}}
