import {VERSION} from './version.js';
const $=id=>document.getElementById(id);
export function organizeMenus(){
 const nav=document.querySelector('.header-right');nav.classList.add('shell-nav');nav.setAttribute('aria-label','Main menu');
 const make=(id,text,action)=>{const b=document.createElement('button');b.id=id;b.className='secondary compact';b.textContent=text;b.onclick=action;return b;};
 const play=make('nav-play','PLAY',()=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();});play.setAttribute('aria-current','page');const maps=make('nav-maps','MAPS',()=>window.neonMaps?.()),friends=make('nav-friends','FRIENDS',()=>window.neonAccount.open('social'));const downloads=nav.querySelector('.download-link');if(downloads){downloads.textContent='GET WINDOWS CLIENT';if(window.neonDesktop)downloads.remove();else document.querySelector('#lobby footer').append(downloads);}const settings=$('settings-open');settings.textContent='SETTINGS';settings.className='secondary compact';nav.replaceChildren(play,maps,$('armory-open'),$('account-open'),friends,settings,$('update-game'));
 for(const b of nav.children)b.addEventListener('click',()=>{for(const other of nav.children)other.removeAttribute('aria-current');b.setAttribute('aria-current','page');});document.addEventListener('close',()=>{if(!document.querySelector('dialog[open]')){for(const b of nav.children)b.removeAttribute('aria-current');play.setAttribute('aria-current','page');}},true);
 document.querySelector('.intro .overline').textContent='NEON BREACH / '+VERSION;document.querySelector('.intro h1').innerHTML='YOUR SQUAD.<br><em>YOUR RULES.</em>';document.querySelector('.lede').textContent='Create a room with friends, join an invite, or play solo.';document.querySelector('.mode-line').textContent='PRIVATE ROOMS · 2–8 SLOTS · SOLO PRACTICE';
 const form=$('settings').querySelector('form'),heading=form.querySelector('.settings-heading'),tabs=document.createElement('nav');tabs.className='account-tabs';tabs.setAttribute('aria-label','Settings categories');const sections={};for(const name of ['Graphics','Controls','Audio','Gameplay']){const section=document.createElement('section');section.id='settings-'+name.toLowerCase();section.className=name==='Graphics'?'':'hidden';sections[name]=section;const b=make('',name.toUpperCase(),()=>{for(const [key,pane]of Object.entries(sections))pane.classList.toggle('hidden',key!==name);for(const other of tabs.children)other.setAttribute('aria-pressed',String(other===b));});b.type='button';b.setAttribute('aria-pressed',String(name==='Graphics'));tabs.append(b);}
 sections.Controls.append(form.querySelector('.controller-settings'));
 function move(id,target){const el=$(id);if(!el)return;const label=form.querySelector('label[for="'+id+'"]');if(label)target.append(label);target.append(el);}
 for(const id of ['quality','render-scale','shadow-quality','effect-quality','frame-limit','atmosphere','fov','motion'])move(id,sections.Graphics);
 const inputBlock=sections.Controls.querySelector('.controller-settings'),pad=document.createElement('section'),kbm=document.createElement('section'),deviceStatus=document.createElement('p');pad.id='controls-ps5';pad.className='control-device';kbm.id='controls-kbm';kbm.className='control-device';deviceStatus.id='controls-active-device';deviceStatus.className='status';const inputSelect=inputBlock.querySelector('#input-mode');let child=inputSelect.nextSibling;while(child){const next=child.nextSibling;pad.append(child);child=next;}inputBlock.append(deviceStatus,kbm,pad);const graphic=document.createElement('div');graphic.className='keyboard-diagram';graphic.setAttribute('aria-label','Keyboard and mouse: WASD movement, mouse aim and fire');graphic.innerHTML='<div class="key-cluster"><kbd>W</kbd><div><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></div><small>MOVE</small></div><div class="mouse-diagram"><span>LEFT<br>FIRE</span><span>RIGHT<br>AIM</span><small>MOUSE</small></div>';kbm.append(graphic);move('sensitivity',kbm);const bindings=form.querySelector('.control-list');if(bindings)kbm.append(bindings);function syncDevice(){const preference=window.neonSettings?.().inputMode||'auto',device=preference==='auto'?(window.neonInputDevice?.()||'kbm'):preference,ps=device==='ps5';pad.hidden=!ps;kbm.hidden=ps;deviceStatus.textContent=(preference==='auto'?'Auto-detect · currently using ':'Selected input · ')+(ps?'PS5 controller':'Keyboard & mouse');}window.addEventListener('neon-input',syncDevice);window.addEventListener('neon-account',syncDevice);syncDevice();for(const id of ['volume','music-volume'])move(id,sections.Audio);for(const id of ['difficulty','reticle'])move(id,sections.Gameplay);
 const note=document.createElement('p');note.className='status';note.textContent='Mode, map, player limit and round rules are in Match Setup. Appearance and profile privacy are in Profile.';sections.Gameplay.append(note);const effects=document.createElement('div');effects.innerHTML='<label for="hit-effect-strength">DAMAGE EFFECT INTENSITY <output id="hit-effect-value"></output></label><input type="range" id="hit-effect-strength" min="0" max="100" step="10"><p class="status">Adjust the edge vignette and directional arc. Damage numbers and health bars stay visible.</p>';sections.Gameplay.append(effects);let intensity=1;try{const saved=localStorage.getItem('neon-hit-effects');if(saved!==null)intensity=Math.max(0,Math.min(1,Number(saved)||0));}catch{}const range=effects.querySelector('input'),value=effects.querySelector('output');const sync=()=>{range.value=Math.round(intensity*100);value.textContent=range.value+'%';};range.oninput=()=>{intensity=Number(range.value)/100;sync();try{localStorage.setItem('neon-hit-effects',String(intensity));}catch{}};window.neonHitIntensity=()=>intensity;sync();form.replaceChildren(heading,tabs,...Object.values(sections));
}
