import {VERSION} from './version.js';
const $=id=>document.getElementById(id);
export function organizeMenus(){
 const nav=document.querySelector('.header-right');nav.classList.add('shell-nav');nav.setAttribute('aria-label','Main menu');
 const make=(id,text,action)=>{const b=document.createElement('button');b.id=id;b.className='secondary compact';b.textContent=text;b.onclick=action;return b;};
 const play=make('nav-play','PLAY',()=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();});play.setAttribute('aria-current','page');const maps=make('nav-maps','MAPS',()=>window.neonMaps?.()),friends=make('nav-friends','FRIENDS',()=>window.neonAccount.open('social'));const downloads=nav.querySelector('.download-link');if(downloads){downloads.textContent='GET WINDOWS CLIENT';if(window.neonDesktop)downloads.remove();else document.querySelector('#lobby footer').append(downloads);}const settings=$('settings-open');settings.textContent='SETTINGS';settings.className='secondary compact';nav.replaceChildren(play,maps,$('armory-open'),$('account-open'),friends,settings,$('update-game'));
 for(const b of nav.children)b.addEventListener('click',()=>{for(const other of nav.children)other.removeAttribute('aria-current');b.setAttribute('aria-current','page');});document.addEventListener('close',()=>{if(!document.querySelector('dialog[open]')){for(const b of nav.children)b.removeAttribute('aria-current');play.setAttribute('aria-current','page');}},true);
 document.querySelector('.intro .overline').textContent='NEON BREACH / '+VERSION;document.querySelector('.intro h1').innerHTML='YOUR SQUAD.<br><em>YOUR RULES.</em>';document.querySelector('.lede').textContent='Six ways to compete. Three places to make your own.';document.querySelector('.mode-line').textContent='PRIVATE ROOMS · 2–8 SLOTS · SOLO PRACTICE';
 const form=$('settings').querySelector('form'),heading=form.querySelector('.settings-heading'),tabs=document.createElement('nav');tabs.className='account-tabs';tabs.setAttribute('aria-label','Settings categories');const sections={};for(const name of ['Graphics','Controls','Audio','Gameplay']){const section=document.createElement('section');section.id='settings-'+name.toLowerCase();section.className=name==='Graphics'?'':'hidden';sections[name]=section;const b=make('',name.toUpperCase(),()=>{for(const [key,pane]of Object.entries(sections))pane.classList.toggle('hidden',key!==name);for(const other of tabs.children)other.setAttribute('aria-pressed',String(other===b));});b.type='button';b.setAttribute('aria-pressed',String(name==='Graphics'));tabs.append(b);}
 sections.Controls.append(form.querySelector('.controller-settings'));
 function move(id,target){const el=$(id);if(!el)return;const label=form.querySelector('label[for="'+id+'"]');if(label)target.append(label);target.append(el);}
 for(const id of ['quality','render-scale','shadow-quality','effect-quality','frame-limit','atmosphere','fov','motion'])move(id,sections.Graphics);
 move('sensitivity',sections.Controls);const bindings=form.querySelector('.control-list');if(bindings)sections.Controls.append(bindings);for(const id of ['volume','music-volume'])move(id,sections.Audio);for(const id of ['difficulty','reticle'])move(id,sections.Gameplay);
 const note=document.createElement('p');note.className='status';note.textContent='Match modes, player limits and round rules are in the room lobby. Appearance and profile privacy are in Profile.';sections.Gameplay.append(note);form.replaceChildren(heading,tabs,...Object.values(sections));
}
