// Original electronic score. Rendered once, then looped by the audio engine (no timer gaps).
export async function makeScore(context){
 const rate=32000,bpm=124,step=60/bpm/4,bars=16,duration=bars*16*step,offline=new OfflineAudioContext(2,Math.ceil(duration*rate),rate),mix=offline.createDynamicsCompressor();mix.threshold.value=-14;mix.ratio.value=3;mix.connect(offline.destination);let seed=8128;
 const noise=offline.createBuffer(1,rate,rate),data=noise.getChannelData(0);for(let i=0;i<data.length;i++){seed=(1664525*seed+1013904223)>>>0;data[i]=seed/2147483648-1;}
 function tone(time,freq,length,level,type='sine',end=freq,pan=0){const o=offline.createOscillator(),g=offline.createGain(),p=offline.createStereoPanner();o.type=type;o.frequency.setValueAtTime(freq,time);o.frequency.exponentialRampToValueAtTime(end,time+length);g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(level,time+.008);g.gain.exponentialRampToValueAtTime(.0001,time+length);p.pan.value=pan;o.connect(g);g.connect(p);p.connect(mix);o.start(time);o.stop(time+length);}
 function hit(time,freq,length,level,type='highpass'){const n=offline.createBufferSource(),f=offline.createBiquadFilter(),g=offline.createGain();n.buffer=noise;f.type=type;f.frequency.value=freq;g.gain.setValueAtTime(level,time);g.gain.exponentialRampToValueAtTime(.0001,time+length);n.connect(f);f.connect(g);g.connect(mix);n.start(time);n.stop(time+length);}
 const hz=n=>440*2**((n-69)/12),roots=[33,41,36,43],arp=[0,7,12,15,7,12,19,12];for(let bar=0;bar<bars;bar++){const root=roots[Math.floor(bar/2)%4];for(let n=0;n<16;n++){const t=(bar*16+n)*step,breakdown=bar===7||bar===15;if(n%4===0&&!breakdown)tone(t,125,.2,.75,'sine',42);if(n%8===4){hit(t,1500,.16,.22,'bandpass');tone(t,185,.12,.12,'triangle',100);}if(n%2===0)hit(t,8000,n%4===2?.08:.035,.09);if([0,3,6,8,11,14].includes(n))tone(t,hz(root+(n===14?12:0)),step*.8,.19,'triangle');if(bar%4>=1||bar>=8){const note=hz(root+24+arp[(n+bar)%8]);tone(t,note,step*1.5,.025,'triangle',note,n%2?.5:-.5);}if(n===0)for(const offset of [0,7,15])tone(t,hz(root+24+offset),step*14,.024,'sine');}}
 const buffer=await offline.startRendering(),source=context.createBufferSource();source.buffer=buffer;source.loop=true;return source;
}

export const TRACKS=[{title:'AI Fight',artist:'Alexander Ehlers',file:'ai-fight.mp3'},{title:'New Factory',artist:'Alexander Ehlers',file:'new-factory.mp3'},{title:'System Overload',artist:'Alexander Ehlers',file:'system-overload.mp3'}];
export function mountMusic(getAudio){
 const pane=document.getElementById('settings-audio'),section=document.createElement('section');section.className='music-player';section.innerHTML='<h3>Arena radio</h3><p class="status">Three full electronic tracks, included and ready to play. Full music in menus; a subtle background mix during combat. Victory and defeat have their own short cues. Starts after your first click.</p><p id="music-status" role="status">Ready · AI Fight — Alexander Ehlers</p><div class="music-actions"><button type="button" id="music-pause">PLAY RADIO</button><button type="button" id="music-next">NEXT SONG</button><button type="button" id="music-original">ORIGINAL SCORE</button></div><ol id="music-queue"></ol><p class="status">Music by Alexander Ehlers · CC0. <a href="https://opengameart.org/content/t-t-free-cyberpunk-pack-2" target="_blank" rel="noopener">Artist &amp; source</a></p>';pane.append(section);
 const $=id=>document.getElementById(id),player=new Audio();player.preload='auto';player.id='arena-radio';section.append(player);let index=0,node,started=false,original=false;
 const status=text=>$('music-status').textContent=text;
 function audio(){const a=getAudio();if(!node){node=a.context.createMediaElementSource(player);node.connect(a.music);}return a;}
 async function play(change=false){started=true;original=false;const a=audio();a.sceneGain.gain.setTargetAtTime(levels[scene]??1,a.context.currentTime,.25);if(change||!player.src)player.src=new URL('./music/'+TRACKS[index].file,import.meta.url).href;try{await player.play();a.scoreGain.gain.value=0;status('Now playing · '+TRACKS[index].title+' — '+TRACKS[index].artist);$('music-pause').textContent='PAUSE MUSIC';for(const [i,b]of [...$('music-queue').querySelectorAll('button')].entries())b.setAttribute('aria-pressed',String(i===index));}catch{a.scoreGain.gain.value=1;status('Radio unavailable · original score is playing. Press Play to retry.');$('music-pause').textContent='PLAY RADIO';}}
 $('music-queue').replaceChildren(...TRACKS.map((track,i)=>{const row=document.createElement('li'),b=document.createElement('button');b.type='button';b.textContent=track.title+' · '+track.artist;b.onclick=()=>{index=i;play(true);};row.append(b);return row;}));
 $('music-original').onclick=()=>{started=true;player.pause();const a=audio();a.scoreGain.gain.value=1;original=true;status('Original score · NIGHT CIRCUIT');$('music-pause').textContent='PLAY RADIO';};$('music-pause').onclick=()=>{if(player.paused||original)play();else{player.pause();status('Paused · '+TRACKS[index].title);$('music-pause').textContent='RESUME MUSIC';}};$('music-next').onclick=()=>{index=(index+1)%TRACKS.length;play(true);};player.onended=()=>$('music-next').click();player.onerror=()=>{if(started){getAudio().scoreGain.gain.value=1;status('Radio unavailable · original score is playing. Press Play to retry.');$('music-pause').textContent='PLAY RADIO';}};
 const start=()=>{if(!started)play();};document.addEventListener('pointerdown',start,{once:true});document.addEventListener('keydown',start,{once:true});
 let scene='lobby',resultTimer;const levels={match:.035,result:.65,room:1,lobby:1};
 function fade(level,seconds=.45){if(!started)return;const a=audio(),g=a.sceneGain.gain,t=a.context.currentTime;g.cancelScheduledValues(t);g.setTargetAtTime(level,t,seconds);section.dataset.mix=String(level);}
 function setScene(next){if(scene===next)return;scene=next;clearTimeout(resultTimer);section.dataset.scene=next;fade(levels[next]??1);}
 function result(outcome){setScene('result');fade(.12,.08);if(started){const a=audio(),t=a.context.currentTime,notes=outcome==='win'?[220,277.18,329.63,440]:outcome==='loss'?[220,196,164.81,146.83]:[220,246.94,220];for(const [i,f]of notes.entries()){const o=a.context.createOscillator(),g=a.context.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(0,t+i*.18);g.gain.linearRampToValueAtTime(Math.max(.0001,.12*a.music.gain.value),t+i*.18+.02);g.gain.exponentialRampToValueAtTime(.0001,t+i*.18+.9);o.connect(g);g.connect(a.context.destination);o.start(t+i*.18);o.stop(t+i*.18+.95);o.onended=()=>{o.disconnect();g.disconnect();};}}resultTimer=setTimeout(()=>{if(scene==='result')fade(.8,.7);},1600);}
 return {setScene,result};

}
