import {MAPS,normalizeRules} from './rules.js';
export function mountPartyUI(link,getState,toast){
 const vote=document.createElement('section');vote.className='map-ballot';vote.innerHTML='<h3>Vote for the next map</h3><p class="ballot-status"></p><div class="ballot-options"></div>';const buttons=[];
 for(const [map,name]of Object.entries(MAPS)){const b=document.createElement('button');b.type='button';b.innerHTML='<img src="./previews/map-'+map+'.png" alt=""><span></span><small></small>';b.querySelector('span').textContent=name;b.onclick=()=>link.party.cast(map);vote.querySelector('.ballot-options').append(b);buttons.push({map,b});}
 const network=document.createElement('p');network.id='party-network';network.setAttribute('role','status');document.body.append(network);let warningUntil=0;
 link.addEventListener('network',e=>{network.textContent=e.detail.state==='waiting'?'Connection interrupted — waiting for '+(link.host?'a player':'the host')+'. Keep this window open.':'Connection restored.';warningUntil=Date.now()+(e.detail.state==='waiting'?18000:3500);});
 const loadout=document.createElement('button');loadout.className='secondary';loadout.textContent='CHOOSE STARTING WEAPON';loadout.onclick=()=>document.getElementById('armory-open').click();document.querySelector('.room-footer').prepend(loadout);
 const presetDialog=document.createElement('dialog');presetDialog.id='match-presets';presetDialog.innerHTML='<div class="settings-heading"><h2>Match presets</h2><button type="button" aria-label="Close presets">×</button></div><p class="status">Save your applied match setup on this device. Save changes in Match Setup first to include them. Loading applies it to your room and clears readiness.</p><label for="preset-name">PRESET NAME</label><input id="preset-name" maxlength="28" placeholder="Friday squad night"><button class="primary" id="save-preset" type="button">SAVE APPLIED SETUP</button><p id="preset-status" role="status"></p><div id="preset-list"></div>';document.body.append(presetDialog);presetDialog.querySelector('.settings-heading button').onclick=()=>presetDialog.close();
 let presets=[];try{presets=JSON.parse(localStorage.getItem('neon-room-presets')||'[]');if(!Array.isArray(presets))presets=[];presets=presets.slice(0,6).filter(p=>typeof p.name==='string'&&p.rules).map(p=>({name:p.name.slice(0,28),rules:normalizeRules(p.rules)}));}catch{}
 const persist=()=>{try{localStorage.setItem('neon-room-presets',JSON.stringify(presets));return true;}catch{document.getElementById('preset-status').textContent='Device storage is unavailable.';}};
 function renderPresets(){const list=document.getElementById('preset-list');list.replaceChildren();for(const [i,p]of presets.entries()){const row=document.createElement('div'),load=document.createElement('button'),remove=document.createElement('button');row.className='saved-preset';load.type=remove.type='button';load.className='secondary';load.textContent=p.name;load.disabled=!window.neonMatchSetup.editable;load.onclick=()=>{if(window.neonMatchSetup.applyRules(p.rules)){presetDialog.close();document.getElementById('match-settings-dialog').close();toast('Preset loaded: '+p.name);}else document.getElementById('preset-status').textContent='Cannot apply this preset now. Check room size or wait for voting to finish.';};remove.className='text-button';remove.textContent='DELETE';remove.setAttribute('aria-label','Delete '+p.name);remove.onclick=()=>{presets.splice(i,1);persist();renderPresets();};row.append(load,remove);list.append(row);}}
 document.getElementById('save-preset').onclick=()=>{const name=document.getElementById('preset-name').value.trim();if(!name){document.getElementById('preset-status').textContent='Enter a name for this preset.';return;}const existing=presets.findIndex(p=>p.name.toLowerCase()===name.toLowerCase());if(existing<0&&presets.length>=6){document.getElementById('preset-status').textContent='Six presets saved. Delete one or reuse its name to replace it.';return;}const p={name,rules:window.neonMatchSetup.current};if(existing>=0)presets[existing]=p;else presets.push(p);const saved=persist();renderPresets();if(saved)document.getElementById('preset-status').textContent='Saved on this device.';};
 const open=document.createElement('button');open.type='button';open.className='secondary';open.textContent='SAVED PRESETS';open.onclick=()=>{renderPresets();presetDialog.showModal();};document.querySelector('#live-rules .rule-actions').append(open);
 let key='';return {update(){const {mode,online}=getState(),v=link.party.vote;network.hidden=!online||Date.now()>warningUntil;vote.hidden=!online||!v||!['room','result'].includes(mode);if(!vote.hidden){const parent=mode==='result'?document.querySelector('#result-screen .modal'):document.querySelector('.room-columns');if(vote.parentElement!==parent){const actions=parent.querySelector('.result-actions');if(actions)parent.insertBefore(vote,actions);else parent.append(vote);}const remaining=Math.max(0,Math.ceil((v.endsAt-Date.now())/1000));vote.querySelector('.ballot-status').textContent=v.result?'Next: '+MAPS[v.result]+' · Continue to your room, choose your weapon, then ready up.':'Choose a map · '+remaining+'s · Ties are randomized; no votes selects a different map.';const next=JSON.stringify(v);if(next!==key){key=next;for(const {map,b}of buttons){b.disabled=!!v.result;b.setAttribute('aria-pressed',String(v.votes[link.side]===map));b.querySelector('small').textContent=Object.values(v.votes).filter(x=>x===map).length+' votes'+(v.result===map?' · WINNER':'');}}}if(mode==='room'&&v&&!v.result){const ready=document.getElementById('ready');ready.disabled=true;ready.textContent='MAP VOTE IN PROGRESS';}loadout.disabled=link.locked;}};
}
