import * as T from 'three';
import {JUMP_PADS} from './systems.js';
const colors=[0xc6a0ff,0x80ffdd,0xffb264];
export function createPowerVisuals(scene,nodes){
 const crystalGeo=new T.OctahedronGeometry(.42),ringGeo=new T.TorusGeometry(.85,.035,6,48),beamGeo=new T.CylinderGeometry(.22,.8,5,12,1,true);
 const pickups=nodes.map(n=>{const root=new T.Group();root.position.set(n.x,.06,n.z);scene.add(root);const mat=new T.MeshStandardMaterial({color:colors[n.type],emissive:colors[n.type],emissiveIntensity:2,roughness:.18,metalness:.5});const crystal=new T.Mesh(crystalGeo,mat);crystal.position.y=1.05;root.add(crystal);const ring=new T.Mesh(ringGeo,mat);ring.rotation.x=Math.PI/2;root.add(ring);const beam=new T.Mesh(beamGeo,new T.MeshBasicMaterial({color:colors[n.type],transparent:true,opacity:.055,blending:T.AdditiveBlending,depthWrite:false,side:T.DoubleSide}));beam.position.y=2.5;root.add(beam);const orbit=new T.Mesh(ringGeo,mat);orbit.scale.setScalar(.6);orbit.position.y=1.05;root.add(orbit);const base=new T.Mesh(new T.CylinderGeometry(1.1,1.2,.1,32),new T.MeshStandardMaterial({color:0x1e3544,metalness:.8,roughness:.3}));root.add(base);return {root,crystal,ring,beam,orbit,mat};});
 const pads=JUMP_PADS.map(p=>{const root=new T.Group();root.position.set(p.x,.035,p.z);scene.add(root);const mat=new T.MeshStandardMaterial({color:0x78caff,emissive:0x3399ff,emissiveIntensity:1.5});const disc=new T.Mesh(new T.CylinderGeometry(1,1.08,.08,32),new T.MeshStandardMaterial({color:0x314f69,metalness:.8,roughness:.2}));root.add(disc);const ring=new T.Mesh(ringGeo,mat);ring.rotation.x=Math.PI/2;ring.position.y=.05;root.add(ring);for(let i=0;i<3;i++){const arrow=new T.Mesh(new T.ConeGeometry(.13,.25,3),mat);arrow.rotation.x=Math.PI/2;arrow.position.set(0,.07,(i-1)*.4);root.add(arrow);}return {ring,mat};});
 return {update(t,state,reduced){pickups.forEach((v,i)=>{const n=state[i],active=n.cool<=0,color=colors[n.type];v.mat.color.setHex(color);v.mat.emissive.setHex(color);v.mat.emissiveIntensity=active?1.9:.15;v.beam.material.color.setHex(color);v.crystal.visible=active;v.orbit.visible=active;v.beam.visible=active;v.ring.scale.setScalar(active?1:.3+.7*(1-n.cool/30));v.crystal.rotation.set(reduced?0:t*.7,t*.8,0);v.crystal.position.y=1.05+(reduced?0:Math.sin(t*2)*.15);v.orbit.rotation.set(1.1,t*.5,.4);v.beam.material.opacity=.035+(reduced?0:Math.sin(t*3)*.015);});pads.forEach(v=>v.mat.emissiveIntensity=reduced?1.3:1.3+Math.sin(t*3)*.35);}};
}
