import {WEAPONS} from './core.js';
import {MODES,normalizeRules} from './rules.js';
const $=id=>document.getElementById(id);
const select=(id,label,options)=>`<div><label for="${id}">${label}</label><select id="${id}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></div>`;
export function mountRoomHub(link){
 for(const id of ['room-mode','live-mode'])$(id).innerHTML=Object.entries(MODES).map(([v,t])=>`<option value="${v}">${t}</option>`).join('');
 $('room-capacity').innerHTML=Array.from({length:7},(_,i)=>`<option value="${i+2}">${i+2} players maximum</option>`).join('');$('room-mode').onchange=()=>{const duel=$('room-mode').value==='duel';$('room-capacity').disabled=duel;if(duel)$('room-capacity').value='2';};$('room-mode').onchange();
 const panel=document.querySelector('.play-panel'),setup=document.createElement('section'),actions=document.createElement('section');setup.className='setup-card';actions.className='action-card';setup.innerHTML='<p class="overline">01 / SET UP</p><h2>Choose your arena.</h2>';actions.innerHTML='<p class="overline">02 / PLAY</p><h2>Bring your squad.</h2>';
 const nickname=$('nickname');setup.append(panel.querySelector('label[for=nickname]'),nickname,...panel.querySelectorAll('.room-options'));actions.append($('host'));const join=document.createElement('div');join.className='join-card';join.innerHTML='<h3>Have an invitation?</h3><p>Paste a room code or invite link.</p>';join.append(panel.querySelector('.join-row'));actions.append(join,$('practice'),$('guide-open'),$('lobby-status'));panel.replaceChildren(setup,actions);$('room-input').maxLength=300;$('room-input').placeholder='CODE OR INVITE LINK';
 const parseCode=()=>{let value=$('room-input').value.trim();try{if(value.includes('://'))value=new URLSearchParams(new URL(value).hash.slice(1)).get('room')||'';}catch{}$('room-input').value=value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,8);};$('join').addEventListener('click',parseCode,true);$('room-input').addEventListener('keydown',e=>{if(e.key==='Enter'){$('join').click();e.preventDefault();}});
 const shell=document.querySelector('.room-modal');const header=document.createElement('header');header.className='room-heading';const title=document.createElement('div');title.append($('room-kicker'),$('room-title'),$('room-description'));const sharing=document.createElement('div');sharing.className='room-sharing';sharing.append($('room-code'),$('copy-invite'),$('room-friends'));const copyCode=document.createElement('button');copyCode.type='button';copyCode.className='text-button';copyCode.textContent='COPY CODE';copyCode.onclick=async()=>{try{await navigator.clipboard.writeText(link.code);copyCode.textContent='COPIED';}catch{copyCode.textContent='CODE: '+link.code;}setTimeout(()=>copyCode.textContent='COPY CODE',2000);};sharing.append(copyCode);header.append(title,sharing);
 const roster=document.createElement('section');roster.className='room-card';roster.innerHTML='<h3>Your squad</h3><p class="status">Ready up when you want to play. Empty slots and uneven teams are welcome.</p>';roster.append($('room-roster'),$('team-choice'));const rules=$('live-rules');rules.classList.add('room-card');rules.querySelector('.field-label').textContent='MATCH SETTINGS';rules.insertAdjacentHTML('beforeend','<div class="rule-fields">'+select('live-capacity','PLAYER LIMIT',Array.from({length:7},(_,i)=>[i+2,i+2+' players']))+'<div><label for="live-limit">SCORE TO WIN / HILL SECONDS</label><input id="live-limit" type="number" min="1" max="600" value="7"></div>'+select('live-time','TIME LIMIT',[[0,'Unlimited'],[180,'3 minutes'],[300,'5 minutes'],[600,'10 minutes'],[900,'15 minutes']])+select('live-respawn','RESPAWN',[[1,'1 second'],[3,'3 seconds'],[5,'5 seconds'],[10,'10 seconds']])+select('live-weapon','LOADOUT',[[-1,'All weapons'],[0,'Rifle only'],[1,'Shotgun only'],[2,'Precision only'],[3,'SMG only'],[4,'Pistol only']])+select('live-rotation','HILL ROTATION',[[15,'15 seconds'],[30,'30 seconds'],[60,'60 seconds']])+'</div><div class="rule-actions"><button id="rules-apply" class="primary" type="button">APPLY SETTINGS</button><button id="rules-fast" class="secondary" type="button">FAST ROUND PRESET</button></div><p id="rules-help" class="status"></p>');
 const pool=document.createElement('fieldset');pool.className='weapon-pool';pool.innerHTML='<legend>ALLOWED WEAPONS</legend><p class="status">Choose any combination. Single-weapon modes override this selection.</p>'+WEAPONS.map((w,i)=>'<label><input type="checkbox" data-allowed="'+i+'" checked> '+w.short+'</label>').join('');rules.querySelector('.rule-actions').before(pool);
 $('live-weapon').onchange=()=>pool.querySelectorAll('input').forEach(el=>el.disabled=!link.host||+$('live-weapon').value>=0);
 let draftDirty=false,lastRules='';rules.addEventListener('change',()=>{if(link.host){draftDirty=true;$('rules-help').textContent='Unsaved changes · Apply settings when you are ready.';}});
 const apply=()=>{const allowedWeapons=[...pool.querySelectorAll('input:checked')].map(el=>+el.dataset.allowed);if(!allowedWeapons.length){$('rules-help').textContent='Select at least one weapon.';return;}draftDirty=false;const ok=link.chooseRules({allowedWeapons,mode:$('live-mode').value,map:$('live-map').value,capacity:+$('live-capacity').value,limit:+$('live-limit').value,timeLimit:+$('live-time').value,respawn:+$('live-respawn').value,weapon:+$('live-weapon').value,hillRotation:+$('live-rotation').value});$('rules-help').textContent=ok?'Settings applied. Everyone needs to ready up again.':'Cannot apply: the room is locked or the player limit is too small.';};$('rules-apply').onclick=apply;$('rules-fast').onclick=()=>{$('live-time').value='180';$('live-respawn').value='1';$('live-limit').value=$('live-mode').value==='hill'?30:10;apply();};
 $('live-mode').onchange=()=>{const defaults=normalizeRules({mode:$('live-mode').value});$('live-limit').value=defaults.limit;$('live-weapon').value=defaults.weapon;$('live-weapon').disabled=!link.host||['instagib','shotgun'].includes(defaults.mode);pool.querySelectorAll('input').forEach(el=>el.disabled=!link.host||defaults.weapon>=0);$('live-capacity').disabled=defaults.mode==='duel'||!link.host;if(defaults.mode==='duel')$('live-capacity').value='2';};$('live-map').onchange=()=>{$('rules-help').textContent='Map selected. Apply settings to share the change.';};
 const chat=document.createElement('section');chat.className='room-card chat-card';chat.innerHTML='<h3>Room chat <small>Only people in this room</small></h3><div id="chat-log" role="log" aria-live="polite"></div><form id="chat-form"><input id="chat-input" maxlength="240" autocomplete="off" placeholder="Say hello to your squad…" aria-label="Room message"><button class="secondary" type="submit">SEND</button></form><p id="chat-status" class="status">Messages last for this room session.</p>';let lastSend=0,unread=0,muted=false;const mute=document.createElement('button');mute.className='text-button';mute.textContent='MUTE CHAT';mute.onclick=()=>{muted=!muted;mute.textContent=muted?'UNMUTE CHAT':'MUTE CHAT';};chat.append(mute);
 $('chat-form')?.remove(); // The new form is not in the document until mounted below.
 const footer=document.createElement('div');footer.className='room-footer';footer.append($('room-status'),$('ready'),$('leave-room'));const body=document.createElement('div');body.className='room-columns';const left=document.createElement('div');left.append(roster,chat);body.append(left,rules);shell.replaceChildren(header,body,footer);
 $('chat-form').onsubmit=e=>{e.preventDefault();const input=$('chat-input'),text=input.value.trim();if(!text)return;if(Date.now()-lastSend<800){$('chat-status').textContent='Give your squad a moment before sending again.';return;}if(link.closed){$('chat-status').textContent='Join a room to chat.';return;}lastSend=Date.now();link.chat(text);input.value='';$('chat-status').textContent='Messages last for this room session.';};
 link.addEventListener('chat',e=>{if(muted)return;const log=$('chat-log'),nearBottom=log.scrollHeight-log.scrollTop-log.clientHeight<40,row=document.createElement('p'),name=document.createElement('b');name.textContent=e.detail.name+': ';row.append(name,document.createTextNode(e.detail.text));log.append(row);while(log.children.length>80)log.firstChild.remove();if(nearBottom)log.scrollTop=log.scrollHeight;});
 const revert=document.createElement('button');revert.type='button';revert.className='text-button';revert.textContent='RESET CHANGES';rules.append(revert);revert.onclick=()=>{draftDirty=false;sync();window.dispatchEvent(new Event('neon-room-render'));};
 let previousCode='';function sync(){const nextRules=JSON.stringify(link.rules);if(draftDirty&&link.host&&!link.locked&&previousCode===link.code&&lastRules===nextRules)return;draftDirty=false;lastRules=nextRules;revert.disabled=!link.host||link.locked;if(link.code!==previousCode){previousCode=link.code;$('chat-log').replaceChildren();}const r=link.rules;pool.querySelectorAll('input').forEach(el=>{el.checked=(r.allowedWeapons||[0,1,2,3,4]).includes(+el.dataset.allowed);el.disabled=!link.host||link.locked||r.weapon>=0;});for(const [id,key]of [['live-mode','mode'],['live-map','map'],['live-capacity','capacity'],['live-limit','limit'],['live-time','timeLimit'],['live-respawn','respawn'],['live-weapon','weapon'],['live-rotation','hillRotation']]){$(id).value=r[key];$(id).disabled=!link.host||link.locked;}if(r.mode==='duel')$('live-capacity').disabled=true;if(['instagib','shotgun'].includes(r.mode))$('live-weapon').disabled=true;$('live-rotation').disabled=!link.host||r.mode!=='hill'||link.locked;for(const id of ['rules-apply','rules-fast'])$(id).disabled=!link.host||link.locked;rules.classList.remove('hidden');$('rules-help').textContent=link.host?'Changes apply to the next round and clear ready status.':'The host controls these settings.';}
 link.addEventListener('roster',sync);window.addEventListener('neon-room-render',sync);
}
