import {normalizeRules,teamCounts,canJoinTeam} from './rules.js';
// Encrypted WebRTC star: the host assigns player IDs and relays guest traffic.
const PREFIX='nb-rift-v5-';
export class DuelLink extends EventTarget{
 constructor(){super();this.peer=null;this.conn=null;this.code='';this.side=0;this.members=[];this.links=new Map();this.closed=true;this.locked=false;this.rtt=0;this.seq=0;this.rules=normalizeRules();}
 emit(type,detail){this.dispatchEvent(new CustomEvent(type,{detail}));}
 randomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from(crypto.getRandomValues(new Uint8Array(8)),n=>chars[n%chars.length]).join('');}
 async open(host,code,name,rules){this.close();this.closed=false;this.host=host;this.side=host?0:-1;this.name=String(name).slice(0,16);this.rules=normalizeRules({...rules,map:rules?.map||(globalThis.document?.getElementById('room-map')?.value)});this.locked=false;this.seq=0;this.members=host?[{side:0,name:this.name,ready:false,team:0,skin:globalThis.neonAccount?.profile?.skin||'mint'}]:[];this.code=host?this.randomCode():String(code).toUpperCase().replace(/[^A-Z2-9]/g,'');if(!/^[A-Z2-9]{8}$/.test(this.code))throw Error('Enter the eight-character room code.');if(!window.Peer)throw Error('Connection library unavailable. Reload and retry.');const peer=this.peer=host?new Peer(PREFIX+this.code,{debug:0}):new Peer({debug:0});
 return new Promise((resolve,reject)=>{let opened=false;this.openTimeout=setTimeout(()=>{if(!opened){reject(Error('Room service timed out. Please retry.'));this.close();}},16000);
 peer.on('open',()=>{if(this.closed||this.peer!==peer)return;opened=true;clearTimeout(this.openTimeout);resolve(this.code);if(!host){this.attach(peer.connect(PREFIX+this.code,{reliable:true,serialization:'json',metadata:{protocol:5,name:this.name,skin:globalThis.neonAccount?.profile?.skin||'mint'}}),0);this.joinTimeout=setTimeout(()=>{if(this.side<0)this.fail('Player connection timed out. Open the game in Chrome or Edge on both computers, keep the host online, and try another network.');},45000);}this.timer=setInterval(()=>this.heartbeat(),2000);});
 peer.on('connection',conn=>{if(this.closed||this.peer!==peer)return;if(!host||this.locked||this.links.size>=this.rules.capacity-1||conn.metadata?.protocol!==5){conn.on('open',()=>{conn.send({t:'reject',reason:this.locked?'Match in progress. Join after this round.':'Room full or game version different. Everyone should reload.'});setTimeout(()=>conn.close(),300);});return;}let side=1;while(this.links.has(side))side++;this.attach(conn,side);});
 peer.on('error',e=>{if(this.closed||this.peer!==peer)return;if(opened&&this.links.size&&['network','socket-error','socket-closed','server-error'].includes(e.type)){try{if(peer.disconnected)peer.reconnect();}catch{}return;}const message=e.type==='peer-unavailable'?'Room not found. Ask the host to create a new room.':'Connection failed. Try creating a fresh room.';if(!opened){clearTimeout(this.openTimeout);reject(Error(message));this.close();}else this.fail(message);});
 peer.on('disconnected',()=>{if(this.closed||this.peer!==peer||peer.destroyed)return;try{peer.reconnect();}catch{this.fail('Room service disconnected. Create a new room.');}});
 });}
 attach(conn,side){const e={conn,side,ch:null,last:performance.now(),seq:new Map(),rtt:0};this.links.set(side,e);this.conn=this.conn||conn;
 conn.on('open',()=>{if(this.closed||this.links.get(side)!==e)return;if(this.host&&(this.locked||this.members.length>=this.rules.capacity)){this.sendOne(e,{t:'reject',reason:'The round started or the room filled while connecting. Join between rounds.'});setTimeout(()=>this.remove(e),300);return;}e.last=performance.now();try{e.ch=conn.peerConnection.createDataChannel('snapshots',{negotiated:true,id:100,ordered:false,maxRetransmits:0});e.ch.onmessage=event=>{try{this.receive(JSON.parse(event.data),e);}catch{}};this.stateChannel=e.ch;}catch{}
 if(this.host){const counts=teamCounts(this.members);const team=counts[0]<=counts[1]?0:1;this.members.push({side,team,skin:['mint','solar','violet','crimson','carbon'].includes(conn.metadata?.skin)?conn.metadata.skin:'mint',name:String(conn.metadata?.name||'Player').replace(/[<>]/g,'').slice(0,16),ready:false});this.sendOne(e,{t:'welcome',side,rules:this.rules});this.roster();}});
 conn.on('data',data=>this.receive(data,e));conn.on('close',()=>this.remove(e));conn.on('error',()=>this.remove(e));}
 sendOne(e,data,fast=false){if(!e?.conn.open)return false;try{if(fast&&e.ch?.readyState==='open'){if(e.ch.bufferedAmount<16000)e.ch.send(JSON.stringify(data));}else if(!fast||!(e.conn.dataChannel?.bufferedAmount>16000))e.conn.send(data);return true;}catch{return false;}}
 receive(data,e){if(this.closed||this.links.get(e.side)!==e||!data||typeof data.t!=='string')return;try{if(JSON.stringify(data).length>24000)return;}catch{return;}e.last=performance.now();if(data.t==='ping'){this.sendOne(e,{t:'pong',time:data.time});return;}if(data.t==='pong'){if(Number.isFinite(data.time)){e.rtt=Math.max(0,Math.round(performance.now()-data.time));this.rtt=Math.max(...[...this.links.values()].map(e=>e.rtt));}return;}
 if(!this.host&&data.t==='reject'){this.fail(String(data.reason||'Room unavailable.'));return;}if(!this.host&&data.t==='welcome'){if(!Number.isInteger(data.side)||data.side<1||data.side>7)return;this.side=data.side;this.rules=normalizeRules(data.rules);clearTimeout(this.joinTimeout);return;}
 if(this.host&&data.t==='team'){this.setTeam(e.side,data.team);return;}
 if(this.host&&data.t==='rules')return;
 if(this.host&&data.t==='roomready'){const p=this.members.find(p=>p.side===e.side);if(p&&!this.locked){p.ready=true;this.roster();}return;}
 if(!this.host&&data.t==='roster'){if(!Array.isArray(data.members)||data.members.length>8)return;this.members=data.members;this.rules=normalizeRules(data.rules);this.emit('roster',this.members);this.emit('connected',{name:this.members.find(p=>p.side===0)?.name||'Host'});return;}
 const source=this.host?e.side:data.side;if(data.t==='state'){if(!Number.isInteger(source)||source<0||source>7||!Number.isInteger(data.seq)||data.seq<=(e.seq.get(source)??-1))return;e.seq.set(source,data.seq);}
 if(this.host&&!['state','shot','switch','reload','boost'].includes(data.t))return;
 this.emit('message',{...data,from:this.host?e.side:0,side:this.host?e.side:data.side});}
 send(data,onlySide=null){if(!this.host)return this.sendOne(this.links.get(0),data);let sent=false;for(const [side,e]of this.links)if(onlySide===null||side===onlySide)sent=this.sendOne(e,data)||sent;return sent;}
 state(player,id){const data={t:'state',id,seq:++this.seq,side:this.side,p:player};for(const e of this.links.values())this.sendOne(e,data,true);}
 relayState(data){if(this.host)for(const [side,e]of this.links)if(side!==data.side)this.sendOne(e,data,true);}
 roster(){if(!this.host)return;this.send({t:'roster',members:this.members,rules:this.rules});this.emit('roster',this.members);this.emit('connected',{name:this.members.find(p=>p.side!==0)?.name||'Waiting'});}
 chooseTeam(team){if(this.host)this.setTeam(this.side,team);else this.send({t:'team',team});}
 setRules(rules){if(!this.host||this.locked)return false;const next=normalizeRules(rules);if(next.capacity<this.members.length){this.emit('notice','That mode or room size cannot fit the players already here.');this.roster();return false;}const enteringTeams=this.rules.mode!=='tdm'&&next.mode==='tdm';this.rules=next;const counts=[0,0];for(const m of this.members){m.ready=false;if(next.mode!=='tdm')m.team=0;else{if(enteringTeams||![0,1].includes(m.team)||counts[m.team]>=next.capacity/2)m.team=counts[0]<=counts[1]?0:1;counts[m.team]++;}}this.roster();return true;}
 chooseRules(rules){if(this.host)return this.setRules(rules);return false;}
 setTeam(side,team){if(this.locked||!canJoinTeam(this.members,side,team,this.rules))return;const p=this.members.find(p=>p.side===side);if(p.team===team)return;p.team=team;for(const m of this.members)m.ready=false;this.roster();}
 ready(){if(this.host){this.members[0].ready=true;this.roster();}else this.send({t:'roomready'});}
 begin(){this.locked=true;for(const m of this.members)m.ready=false;}
 end(){this.locked=false;}
 heartbeat(){const now=performance.now();for(const e of [...this.links.values()]){if(now-e.last>(e.conn.open?18000:45000)){this.remove(e);continue;}this.sendOne(e,{t:'ping',time:now});}}
 remove(e){if(this.closed||this.links.get(e.side)!==e)return;this.links.delete(e.side);e.ch?.close();e.conn.close();this.conn=[...this.links.values()][0]?.conn||null;if(!this.host){this.fail(this.side<0?'Could not establish the player connection. Open in Chrome or Edge and try another network.':'The host left. Create or join another room.');return;}this.members=this.members.filter(p=>p.side!==e.side);this.roster();this.emit('left',{side:e.side});}
 fail(message){if(this.closed)return;this.close();this.emit('failure',message);}
 close(){this.closed=true;clearInterval(this.timer);clearTimeout(this.openTimeout);clearTimeout(this.joinTimeout);for(const e of this.links.values()){e.ch?.close();e.conn.close();}this.links.clear();this.conn=null;this.stateChannel=null;this.peer?.destroy();this.peer=null;this.members=[];}
}
