import {WEAPONS} from './core.js';
import {MODES,MAPS,normalizeRules} from './rules.js';
const $=id=>document.getElementById(id);
const select=(id,label,options)=>`<div><label for="${id}">${label}</label><select id="${id}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></div>`;
export function mountRoomHub(link){
 for(const id of ['room-map','live-map'])$(id).innerHTML=Object.entries(MAPS).map(([v,t])=>`<option value="${v}">${t}</option>`).join('');
 for(const id of ['room-mode','live-mode'])$(id).innerHTML=Object.entries(MODES).map(([v,t])=>`<option value="${v}">${t}</option>`).join('');
 $('room-capacity').innerHTML=Array.from({length:7},(_,i)=>`<option value="${i+2}">${i+2} players maximum</option>`).join('');$('room-mode').onchange=()=>{const duel=$('room-mode').value==='duel';$('room-capacity').disabled=duel;if(duel)$('room-capacity').value='2';};$('room-mode').onchange();
 const panel=document.querySelector('.play-panel'),setup=document.createElement('section'),actions=document.createElement('section');setup.className='setup-card';actions.className='action-card';setup.innerHTML='<p class="overline">MATCH SETUP</p><h2>Your next match.</h2>';actions.innerHTML='<p class="overline">PLAY</p><h2>Ready to play?</h2>';
 const nickname=$('nickname');setup.append(panel.querySelector('label[for=nickname]'),nickname,...panel.querySelectorAll('.room-options'));actions.append($('host'));const join=document.createElement('div');join.className='join-card';join.innerHTML='<h3>Have an invitation?</h3><p>Paste a room code or invite link.</p>';join.append(panel.querySelector('.join-row'));actions.append(join,$('practice'),$('guide-open'),$('lobby-status'));panel.replaceChildren(setup,actions);$('room-input').maxLength=300;$('room-input').placeholder='CODE OR INVITE LINK';
 const parseCode=()=>{let value=$('room-input').value.trim();try{if(value.includes('://'))value=new URLSearchParams(new URL(value).hash.slice(1)).get('room')||'';}catch{}$('room-input').value=value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,8);};$('join').addEventListener('click',parseCode,true);$('room-input').addEventListener('keydown',e=>{if(e.key==='Enter'){$('join').click();e.preventDefault();}});
 const shell=document.querySelector('.room-modal');const header=document.createElement('header');header.className='room-heading';const title=document.createElement('div');title.append($('room-kicker'),$('room-title'),$('room-description'));const sharing=document.createElement('div');sharing.className='room-sharing';sharing.append($('room-code'),$('copy-invite'),$('room-friends'));const copyCode=document.createElement('button');copyCode.type='button';copyCode.className='text-button';copyCode.textContent='COPY CODE';copyCode.onclick=async()=>{try{await navigator.clipboard.writeText(link.code);copyCode.textContent='COPIED';}catch{copyCode.textContent='CODE: '+link.code;}setTimeout(()=>copyCode.textContent='COPY CODE',2000);};sharing.append(copyCode);header.append(title,sharing);
 const roster=document.createElement('section');roster.className='room-card';roster.innerHTML='<h3>Your squad</h3><p class="status">Select a player to view their profile.</p>';roster.append($('room-roster'),$('team-choice'));const rules=$('live-rules');rules.classList.add('room-card');rules.querySelector('.field-label').textContent='MATCH SETTINGS';rules.insertAdjacentHTML('beforeend','<div class="rule-fields">'+select('live-protection','SPAWN PROTECTION',[[0,'Off'],[.5,'0.5 seconds'],[1,'1 second'],[1.5,'1.5 seconds'],[2,'2 seconds'],[3,'3 seconds'],[5,'5 seconds']])+select('live-capacity','PLAYER LIMIT',Array.from({length:7},(_,i)=>[i+2,i+2+' players']))+'<div><label for="live-limit">SCORE TO WIN / HILL SECONDS</label><input id="live-limit" type="number" min="1" max="600" value="7"></div>'+select('live-time','TIME LIMIT',[[0,'Unlimited'],[180,'3 minutes'],[300,'5 minutes'],[600,'10 minutes'],[900,'15 minutes']])+select('live-respawn','RESPAWN',[[1,'1 second'],[3,'3 seconds'],[5,'5 seconds'],[10,'10 seconds']])+select('live-weapon','LOADOUT',[[-1,'All weapons'],[0,'Rifle only'],[1,'Shotgun only'],[2,'Precision only'],[3,'SMG only'],[4,'Pistol only']])+select('live-rotation','HILL ROTATION',[[15,'15 seconds'],[30,'30 seconds'],[60,'60 seconds']])+'</div><div class="rule-actions"><button id="rules-apply" class="primary" type="button">APPLY SETTINGS</button><button id="rules-fast" class="secondary" type="button">FAST ROUND PRESET</button></div><p id="rules-help" class="status"></p>');
 const vitals=document.createElement('div');vitals.className='vitals-rules';vitals.innerHTML='<h3>Health & shield</h3>'+select('live-health','MAX HEALTH',[[50,'50'],[100,'100'],[150,'150'],[200,'200'],[300,'300']])+select('live-shield','STARTING / MAX SHIELD',[[0,'Off'],[50,'50'],[100,'100'],[150,'150'],[200,'200'],[300,'300']])+select('live-regen','HEALTH REGENERATION',[[0,'Off'],[2,'2 HP / second'],[5,'5 HP / second'],[10,'10 HP / second'],[20,'20 HP / second']])+select('live-regen-delay','DELAY AFTER DAMAGE',[[0,'Immediately'],[3,'3 seconds'],[5,'5 seconds'],[10,'10 seconds'],[15,'15 seconds']])+'<p class="status">Shield absorbs damage before health. Regeneration restores health only, after you stop taking damage. Respawning restores both. Spawn protection blocks incoming damage and firing for the selected duration.</p>';rules.querySelector('.rule-fields').append(vitals);
 const pool=document.createElement('fieldset');pool.className='weapon-pool';pool.innerHTML='<legend>ALLOWED WEAPONS</legend><p class="status">Choose any combination. Single-weapon modes override this selection.</p>'+WEAPONS.map((w,i)=>'<label><input type="checkbox" data-allowed="'+i+'" checked> '+w.short+'</label>').join('');rules.querySelector('.rule-actions').before(pool);
 $('live-weapon').onchange=()=>pool.querySelectorAll('input').forEach(el=>el.disabled=!link.host||+$('live-weapon').value>=0);
 let setupRules;try{setupRules=normalizeRules(JSON.parse(localStorage.getItem('neon-match-setup')||'{}'));}catch{setupRules=normalizeRules();}
 const inRoom=()=>!link.closed&&link.members.some(m=>m.side===link.side),canEdit=()=>!inRoom()||link.host&&!link.locked&&(!link.party.vote||link.party.vote.result),currentRules=()=>inRoom()?link.rules:setupRules;
 let draftDirty=false,lastRules='',opener=null;
 const editor=document.createElement('dialog');editor.id='match-settings-dialog';editor.innerHTML='<div class="settings-heading"><div><p class="overline">NEXT ROUND</p><h2>Match setup.</h2></div><button type="button" class="icon-button" aria-label="Close match setup">×</button></div>';document.body.append(editor);
 const summary=document.createElement('section');summary.id='room-setup-summary';summary.className='room-card match-summary';
 const homeSummary=document.createElement('section');homeSummary.id='home-setup-summary';homeSummary.className='match-summary';setup.append(homeSummary);
 for(const el of setup.querySelectorAll('.room-options'))el.hidden=true;
 function persist(){try{localStorage.setItem('neon-match-setup',JSON.stringify(setupRules));}catch{}$('room-mode').value=setupRules.mode;$('room-map').value=setupRules.map;$('room-capacity').value=String(setupRules.capacity);window.dispatchEvent(new Event('neon-setup-change'));}
 function summaryContent(el,r,room){el.replaceChildren();const img=document.createElement('img');img.src='./previews/map-'+r.map+'.png';img.alt=MAPS[r.map];const title=document.createElement('h3');title.textContent=MODES[r.mode];const detail=document.createElement('p');detail.textContent=MAPS[r.map]+' · '+r.capacity+' player slots';const meta=document.createElement('p');meta.className='status';meta.textContent=(r.mode==='hill'?r.limit+' seconds on the hill':r.limit+' eliminations')+' · '+(r.timeLimit?r.timeLimit/60+' minute limit':'No time limit');const button=document.createElement('button');button.type='button';button.className='secondary';button.id=room?'edit-room-setup':'edit-match-setup';button.textContent=room&&!canEdit()?'VIEW MATCH SETTINGS':'EDIT MATCH SETUP';button.onclick=()=>{opener=button.id;sync(true);editor.showModal();};const vitals=document.createElement('p');vitals.className='status';vitals.textContent=r.spawnProtection+'s SPAWN PROTECTION · '+r.maxHealth+' HEALTH · '+r.maxShield+' SHIELD · '+(r.regenRate?r.regenRate+' HP/s after '+r.regenDelay+'s':'Health regeneration off');el.append(img,title,detail,meta,vitals,button);}
 function refreshSummary(){summaryContent(homeSummary,setupRules,false);summaryContent(summary,currentRules(),true);}
 const closeEditor=()=>editor.close();editor.querySelector('button').onclick=closeEditor;editor.addEventListener('close',()=>{draftDirty=false;sync(true);$(opener)?.focus();});
 function markDirty(){if(!canEdit())return;draftDirty=true;$('rules-apply').disabled=false;$('rules-help').textContent='Unsaved changes. Save to use these settings, or Cancel to keep your current setup.';}
 rules.addEventListener('change',markDirty);rules.addEventListener('input',markDirty);
 function readDraft(){return normalizeRules({spawnProtection:+$('live-protection').value,maxHealth:+$('live-health').value,maxShield:+$('live-shield').value,regenRate:+$('live-regen').value,regenDelay:+$('live-regen-delay').value,allowedWeapons:[...pool.querySelectorAll('input:checked')].map(el=>+el.dataset.allowed),mode:$('live-mode').value,map:$('live-map').value,capacity:+$('live-capacity').value,limit:+$('live-limit').value,timeLimit:+$('live-time').value,respawn:+$('live-respawn').value,weapon:normalizeRules({mode:$('live-mode').value}).weapon,hillRotation:+$('live-rotation').value});}
 const apply=()=>{if(!canEdit())return;const next=readDraft();if(next.weapon<0&&!pool.querySelector('input:checked')){$('rules-help').textContent='Choose at least one allowed weapon.';return;}if(!$('live-limit').checkValidity()){$('live-limit').reportValidity();return;}const changed=JSON.stringify(next)!==JSON.stringify(normalizeRules(currentRules()));if(inRoom()&&changed&&!link.chooseRules(next)){$('rules-help').textContent='This player limit cannot fit your current squad. Choose a larger room.';return;}setupRules=next;persist();draftDirty=false;sync(true);closeEditor();};$('rules-apply').textContent='SAVE CHANGES';$('rules-apply').onclick=apply;$('rules-fast').textContent='USE QUICK MATCH PRESET';$('rules-fast').onclick=()=>{$('live-time').value='180';$('live-respawn').value='1';$('live-limit').value=$('live-mode').value==='hill'?30:10;markDirty();window.dispatchEvent(new Event('neon-choices-refresh'));};
 $('live-mode').onchange=()=>{const defaults=normalizeRules({mode:$('live-mode').value});$('live-limit').value=defaults.limit;$('live-limit').max=defaults.mode==='hill'?600:100;$('live-weapon').value=defaults.weapon;$('live-weapon').disabled=!canEdit()||['instagib','shotgun'].includes(defaults.mode);pool.querySelectorAll('input').forEach(el=>{el.disabled=!canEdit()||defaults.weapon>=0;el.checked=defaults.weapon<0||+el.dataset.allowed===defaults.weapon;});document.querySelector('label[for=live-limit]').textContent=defaults.mode==='hill'?'HILL TIME TO WIN (SECONDS)':'ELIMINATIONS TO WIN';$('live-capacity').disabled=defaults.mode==='duel'||!canEdit();if(defaults.mode==='duel')$('live-capacity').value='2';$('live-rotation').disabled=!canEdit()||defaults.mode!=='hill';};$('live-map').onchange=()=>{};$('live-weapon').onchange=()=>pool.querySelectorAll('input').forEach(el=>el.disabled=!canEdit()||+$('live-weapon').value>=0);
 const chat=document.createElement('section');chat.className='room-card chat-card';chat.innerHTML='<h3>Room chat <small>Only people in this room</small></h3><div id="chat-log" role="log" aria-live="polite"></div><form id="chat-form"><input id="chat-input" maxlength="240" autocomplete="off" placeholder="Say hello to your squad…" aria-label="Room message"><button class="secondary" type="submit">SEND</button></form><p id="chat-status" class="status">Messages last for this room session.</p>';let lastSend=0,unread=0,muted=false;const mute=document.createElement('button');mute.className='text-button';mute.textContent='MUTE CHAT';mute.onclick=()=>{muted=!muted;mute.textContent=muted?'UNMUTE CHAT':'MUTE CHAT';};chat.append(mute);
 $('chat-form')?.remove(); // The new form is not in the document until mounted below.
 const footer=document.createElement('div');footer.className='room-footer';footer.append($('room-status'),$('ready'),$('leave-room'));const body=document.createElement('div');body.className='room-columns';const left=document.createElement('div');left.append(roster,chat);body.append(left,summary);editor.append(rules);shell.replaceChildren(header,body,footer);
 $('chat-form').onsubmit=e=>{e.preventDefault();const input=$('chat-input'),text=input.value.trim();if(!text)return;if(Date.now()-lastSend<800){$('chat-status').textContent='Give your squad a moment before sending again.';return;}if(link.closed){$('chat-status').textContent='Join a room to chat.';return;}lastSend=Date.now();link.chat(text);input.value='';$('chat-status').textContent='Messages last for this room session.';};
 link.addEventListener('chat',e=>{if(muted)return;const log=$('chat-log'),nearBottom=log.scrollHeight-log.scrollTop-log.clientHeight<40,row=document.createElement('p'),name=document.createElement('b');name.textContent=e.detail.name+': ';row.append(name,document.createTextNode(e.detail.text));log.append(row);while(log.children.length>80)log.firstChild.remove();if(nearBottom)log.scrollTop=log.scrollHeight;});
 const cancel=document.createElement('button');cancel.type='button';cancel.className='secondary';cancel.id='rules-cancel';cancel.textContent='CANCEL';rules.querySelector('.rule-actions').append(cancel);cancel.onclick=closeEditor;
 let previousCode='';function sync(force=false){refreshSummary();const r=normalizeRules(currentRules()),nextRules=JSON.stringify(r);if(!force&&draftDirty&&editor.open&&lastRules===nextRules)return;draftDirty=false;lastRules=nextRules;if(link.code!==previousCode){previousCode=link.code;$('chat-log').replaceChildren();}const editable=canEdit();pool.querySelector('p').textContent=['instagib','shotgun'].includes(r.mode)?MODES[r.mode]+' uses '+WEAPONS[r.weapon].short+' only.':'Choose the weapons available in this match. Your starting weapon is selected in Armory.';pool.querySelectorAll('input').forEach(el=>{el.checked=(r.weapon>=0?[r.weapon]:r.allowedWeapons).includes(+el.dataset.allowed);el.disabled=!editable||['instagib','shotgun'].includes(r.mode);});for(const [id,key]of [['live-protection','spawnProtection'],['live-health','maxHealth'],['live-shield','maxShield'],['live-regen','regenRate'],['live-regen-delay','regenDelay'],['live-mode','mode'],['live-map','map'],['live-capacity','capacity'],['live-limit','limit'],['live-time','timeLimit'],['live-respawn','respawn'],['live-weapon','weapon'],['live-rotation','hillRotation']]){$(id).value=r[key];$(id).disabled=!editable;}if(r.mode==='duel')$('live-capacity').disabled=true;if(['instagib','shotgun'].includes(r.mode))$('live-weapon').disabled=true;$('live-rotation').disabled=!editable||r.mode!=='hill';$('live-limit').max=r.mode==='hill'?600:100;document.querySelector('label[for=live-limit]').textContent=r.mode==='hill'?'HILL TIME TO WIN (SECONDS)':'ELIMINATIONS TO WIN';$('rules-apply').hidden=!editable;$('rules-apply').disabled=true;$('rules-fast').hidden=!editable;cancel.textContent=editable?'CANCEL':'CLOSE';rules.classList.remove('hidden');$('rules-help').textContent=inRoom()?(editable?'Changes apply to this room and clear ready status.':'Only the host can change these settings.'):'Used for your next room or solo practice. You will not need to choose again.';window.dispatchEvent(new Event('neon-choices-refresh'));}
 window.neonMatchSetup={applyRules(value){if(!canEdit())return false;const next=normalizeRules(value);if(inRoom()&&!link.chooseRules(next))return false;setupRules=next;persist();sync(true);return true;},get rules(){return normalizeRules(setupRules);},get current(){return normalizeRules(currentRules());},get inRoom(){return inRoom();},get editable(){return canEdit();},chooseMap(map){if(!canEdit()||!MAPS[map])return false;const next=normalizeRules({...currentRules(),map});if(inRoom()&&JSON.stringify(next)!==JSON.stringify(link.rules)&&!link.chooseRules(next))return false;setupRules=next;persist();sync(true);return true;}};
 link.addEventListener('roster',()=>sync());window.addEventListener('neon-room-render',()=>sync());persist();sync(true);

}
