export const MODES={duel:'1v1 Duel',dm:'Deathmatch',hill:'King of the Hill',tdm:'Team Deathmatch',instagib:'Instagib',shotgun:'Shotgun Skirmish'};
export const MAPS={rift:'Orbital Rift',foundry:'Solar Foundry',citadel:'Eclipse Citadel',archive:'Prism Archive',dockyard:'Tempest Dockyard'};
export const TEAM_NAMES=['CYAN','AMBER'];
export const HILLS=[{x:0,z:9},{x:12,z:7},{x:0,z:-9},{x:-12,z:-7}];
export const SPAWNS=[[0,16],[0,-16],[-11,16],[11,-16],[11,16],[-11,-16],[-22,12],[22,-12]];
export function normalizeRules(value={}){const mode=Object.hasOwn(MODES,value.mode)?value.mode:'duel',map=Object.hasOwn(MAPS,value.map)?value.map:'rift';const number=(v,min,max,fallback)=>Number.isFinite(+v)&&v!==undefined?Math.max(min,Math.min(max,Math.round(+v))):fallback;return {mode,map,maxHealth:number(value.maxHealth,25,300,100),maxShield:number(value.maxShield,0,300,100),regenRate:number(value.regenRate,0,50,0),regenDelay:number(value.regenDelay,0,30,5),capacity:mode==='duel'?2:number(value.capacity,2,8,4),limit:number(value.limit,1,mode==='hill'?600:100,mode==='hill'?60:mode==='duel'?7:mode==='tdm'?30:15),timeLimit:[0,180,300,600,900].includes(+value.timeLimit)?+value.timeLimit:0,respawn:number(value.respawn,1,10,3),hillRotation:[15,30,60].includes(+value.hillRotation)?+value.hillRotation:30,allowedWeapons:Array.isArray(value.allowedWeapons)&&value.allowedWeapons.some(n=>Number.isInteger(n)&&n>=0&&n<5)?[...new Set(value.allowedWeapons.filter(n=>Number.isInteger(n)&&n>=0&&n<5))]:[0,1,2,3,4],weapon:mode==='instagib'?2:mode==='shotgun'?1:[-1,0,1,2,3,4].includes(+value.weapon)?+value.weapon:-1};}
export const startingWeapon=rules=>rules.weapon>=0?rules.weapon:(rules.allowedWeapons?.[0]??0);
export const weaponAllowed=(gun,rules)=>Number.isInteger(gun)&&gun>=0&&gun<5&&(rules.weapon>=0?gun===rules.weapon:!rules.allowedWeapons||rules.allowedWeapons.includes(gun));
export function timedWinner(players,rules,teamScores){if(rules.mode==='tdm'){if(teamScores[0]===teamScores[1])return -1;return players.find(p=>p.team===(teamScores[0]>teamScores[1]?0:1))?.side??-1;}const sorted=players.slice().sort((a,b)=>points(b,rules)-points(a,rules));return !sorted.length||sorted[1]&&points(sorted[0],rules)===points(sorted[1],rules)?-1:sorted[0].side;}
export function sameTeam(a,b,rules){return rules.mode==='tdm'&&a&&b&&Number.isInteger(a.team)&&a.team===b.team;}
export function teamCounts(members){return [0,1].map(team=>members.filter(p=>p.team===team).length);}
export function canJoinTeam(members,side,team,rules){return rules.mode==='tdm'&&[0,1].includes(team)&&members.some(p=>p.side===side)&&members.filter(p=>p.side!==side&&p.team===team).length<Math.ceil(rules.capacity/2);}
// Capacity is a ceiling. Neither full nor balanced teams are required.
export function canStartRoom(members,rules){return members.length>0&&members.length<=rules.capacity&&members.every(p=>p.ready)&&(rules.mode!=='tdm'||members.every(p=>[0,1].includes(p.team))&&teamCounts(members).every(n=>n<=Math.ceil(rules.capacity/2)));}
export function points(p,rules){return rules.mode==='hill'?(p.hill||0):p.score;}
export function hillState(elapsed,players,rules={}){const rotation=rules.hillRotation||30,index=Math.floor(elapsed/rotation)%HILLS.length,center=HILLS[index],inside=players.filter(p=>p.dead<=0&&p.shield<=0&&p.y<1.2&&Math.hypot(p.x-center.x,p.z-center.z)<3.8);return {index,center,remaining:rotation-elapsed%rotation,owner:inside.length===1?inside[0].side:null,contested:inside.length>1};}
export function tickHill(elapsed,dt,players,rules={}){const h=hillState(elapsed,players,rules);if(h.owner!==null){const p=players.find(p=>p.side===h.owner);p.hill=Math.min(rules.limit||60,(p.hill||0)+dt);}return h;}
