export const MODES={duel:'1v1 Duel',dm:'Deathmatch',hill:'King of the Hill',teamhill:'Team King of the Hill',tdm:'Team Deathmatch',instagib:'Instagib',shotgun:'Shotgun Skirmish'};
export const isTeamMode=r=>['tdm','teamhill'].includes(typeof r==='string'?r:r.mode);
export const isHillMode=r=>['hill','teamhill'].includes(typeof r==='string'?r:r.mode);
export const MAPS={rift:'Orbital Rift',foundry:'Solar Foundry',citadel:'Eclipse Citadel',archive:'Prism Archive',dockyard:'Tempest Dockyard'};
export const TEAM_NAMES=['CYAN','AMBER'];
export const HILLS=[{x:0,z:9},{x:12,z:7},{x:0,z:-9},{x:-12,z:-7}];
export const SPAWNS=[[0,16],[0,-16],[-11,16],[11,-16],[11,16],[-11,-16],[-22,12],[22,-12]];
export function normalizeRules(value={}){const mode=Object.hasOwn(MODES,value.mode)?value.mode:'duel',map=Object.hasOwn(MAPS,value.map)?value.map:'rift';const number=(v,min,max,fallback)=>Number.isFinite(+v)&&v!==undefined?Math.max(min,Math.min(max,Math.round(+v))):fallback;return {mode,map,spawnProtection:[0,.5,1,1.5,2,3,5].includes(value.spawnProtection)?value.spawnProtection:1.5,hillSeed:number(value.hillSeed,0,2147483647,0),maxHealth:number(value.maxHealth,25,300,100),maxShield:number(value.maxShield,0,300,100),regenRate:number(value.regenRate,0,50,0),regenDelay:number(value.regenDelay,0,30,5),capacity:mode==='duel'?2:number(value.capacity,2,8,4),limit:number(value.limit,1,isHillMode(mode)?600:100,isHillMode(mode)?60:mode==='duel'?7:isTeamMode(mode)?30:15),timeLimit:[0,180,300,600,900].includes(+value.timeLimit)?+value.timeLimit:0,respawn:number(value.respawn,1,10,3),hillRotation:[15,30,60].includes(+value.hillRotation)?+value.hillRotation:30,allowedWeapons:Array.isArray(value.allowedWeapons)&&value.allowedWeapons.some(n=>Number.isInteger(n)&&n>=0&&n<5)?[...new Set(value.allowedWeapons.filter(n=>Number.isInteger(n)&&n>=0&&n<5))]:[0,1,2,3,4],weapon:mode==='instagib'?2:mode==='shotgun'?1:[-1,0,1,2,3,4].includes(+value.weapon)?+value.weapon:-1};}
export const startingWeapon=rules=>rules.weapon>=0?rules.weapon:(rules.allowedWeapons?.[0]??0);
export const weaponAllowed=(gun,rules)=>Number.isInteger(gun)&&gun>=0&&gun<5&&(rules.weapon>=0?gun===rules.weapon:!rules.allowedWeapons||rules.allowedWeapons.includes(gun));
export function timedWinner(players,rules,teamScores){if(isTeamMode(rules)){if(teamScores[0]===teamScores[1])return -1;return players.find(p=>p.team===(teamScores[0]>teamScores[1]?0:1))?.side??-1;}const sorted=players.slice().sort((a,b)=>points(b,rules)-points(a,rules));return !sorted.length||sorted[1]&&points(sorted[0],rules)===points(sorted[1],rules)?-1:sorted[0].side;}
export function sameTeam(a,b,rules){return isTeamMode(rules)&&a&&b&&Number.isInteger(a.team)&&a.team===b.team;}
export function teamCounts(members){return [0,1].map(team=>members.filter(p=>p.team===team).length);}
export function canJoinTeam(members,side,team,rules){return isTeamMode(rules)&&[0,1].includes(team)&&members.some(p=>p.side===side)&&members.filter(p=>p.side!==side&&p.team===team).length<Math.ceil(rules.capacity/2);}
// Capacity is a ceiling. Neither full nor balanced teams are required.
export function canStartRoom(members,rules){return members.length>0&&members.length<=rules.capacity&&members.every(p=>p.bot||p.ready)&&(!isTeamMode(rules)||members.every(p=>[0,1].includes(p.team))&&teamCounts(members).every(n=>n<=Math.ceil(rules.capacity/2)));}
export function points(p,rules){return isHillMode(rules)?(p.hill||0):p.score;}
export function hillState(elapsed,players,rules={}){const rotation=rules.hillRotation||30,round=Math.floor(elapsed/rotation),index=hillIndex(round,rules.hillSeed),center=HILLS[index],inside=players.filter(p=>p.dead<=0&&p.shield<=0&&p.y<1.2&&Math.hypot(p.x-center.x,p.z-center.z)<3.8);return {index,center,next:HILLS[hillIndex(round+1,rules.hillSeed)],nextIndex:hillIndex(round+1,rules.hillSeed),remaining:rotation-elapsed%rotation,owner:inside.length&&(isTeamMode(rules)?new Set(inside.map(p=>p.team)).size===1:inside.length===1)?inside[0].side:null,team:inside.length&&isTeamMode(rules)&&new Set(inside.map(p=>p.team)).size===1?inside[0].team:null,contested:isTeamMode(rules)?new Set(inside.map(p=>p.team)).size>1:inside.length>1};}
export function tickHill(elapsed,dt,players,rules={},teamScores=[0,0]){const h=hillState(elapsed,players,rules);if(h.owner!==null){if(isTeamMode(rules)){teamScores[h.team]=Math.min(rules.limit||60,teamScores[h.team]+dt);for(const p of players.filter(p=>p.team===h.team))p.hill=teamScores[h.team];}else{const p=players.find(p=>p.side===h.owner);p.hill=Math.min(rules.limit||60,(p.hill||0)+dt);}}return h;}

const hillSequences=new Map();
export function hillIndex(round,seed=0){if(!seed)return round%HILLS.length;let sequence=hillSequences.get(seed);if(!sequence){if(hillSequences.size>24)hillSequences.clear();sequence=[];hillSequences.set(seed,sequence);}while(sequence.length<=round){let n=(seed+sequence.length*2654435761)>>>0;const order=[0,1,2,3];for(let i=3;i>0;i--){n=(n+0x6D2B79F5)>>>0;let t=Math.imul(n^n>>>15,1|n);t^=t+Math.imul(t^t>>>7,61|t);const j=((t^t>>>14)>>>0)%(i+1);[order[i],order[j]]=[order[j],order[i]];}if(order[0]===sequence.at(-1))[order[0],order[1]]=[order[1],order[0]];sequence.push(...order);}return sequence[round];}
