import {VERSION} from './version.js';
const $=id=>document.getElementById(id),bridge=window.neonDesktop;
const button=$('update-game');button.classList.remove('hidden');button.textContent='UPDATES';
const box=document.createElement('dialog');box.id='update-panel';box.innerHTML='<div class="settings-heading"><div><p class="overline">NEON BREACH UPDATES</p><h2>Stay in the arena.</h2></div><button id="update-close" class="icon-button" aria-label="Close updates">×</button></div><p id="update-version" class="status"></p><h3 id="update-title"></h3><p id="update-detail" class="status" role="status"></p><progress id="update-progress" max="100" value="0" class="hidden"></progress><div class="update-actions"><button id="update-action" class="primary">CHECK FOR UPDATES</button><button id="update-cancel" class="secondary hidden">CANCEL DOWNLOAD</button></div><p class="status">Updates keep your saved account and settings. Restart when you have finished playing.</p>';document.body.append(box);
let state={phase:'idle',current:VERSION},registration,activating=false;
function render(next){state=next;$('update-version').textContent=(bridge?'WINDOWS CLIENT':'BROWSER VERSION')+' · '+state.current;const titles={idle:'Ready when you are.',checking:'Checking for updates…',available:'A new version is available.',downloading:'Downloading update…',ready:bridge?'Ready to restart and install.':'Update ready to reload.',current:'You are up to date.',error:'Update could not finish.',unsupported:'Desktop updates are unavailable here.',installing:'Restarting to install…'};$('update-title').textContent=titles[state.phase]||'';$('update-detail').textContent=state.error||state.notes||'';const busy=['checking','downloading','installing'].includes(state.phase);$('update-action').disabled=busy;$('update-action').textContent=state.phase==='ready'?(bridge?'RESTART & INSTALL':'RELOAD TO UPDATE'):state.phase==='available'&&bridge?'DOWNLOAD UPDATE':'CHECK FOR UPDATES';$('update-progress').classList.toggle('hidden',state.phase!=='downloading');$('update-progress').value=state.progress||0;if(state.phase==='downloading')$('update-detail').textContent=(state.total?state.progress+'% · ':'')+Math.round((state.received||0)/1048576)+' MB downloaded';$('update-cancel').classList.toggle('hidden',!bridge||state.phase!=='downloading');button.textContent=['available','ready'].includes(state.phase)?'UPDATE AVAILABLE':'UPDATES';}
async function browserCheck(){render({...state,phase:'checking',error:''});try{if(!registration)throw Error('Browser updates need an online HTTPS connection. Reload when connected.');await registration.update();if(registration.waiting)render({...state,phase:'ready'});else if(!registration.installing)render({...state,phase:'current'});}catch(e){render({...state,phase:'error',error:e.message});}}
async function open(){if(document.pointerLockElement)document.exitPointerLock();if(!box.open)box.showModal();if(bridge)render(await bridge.state());else render(state);}
button.onclick=open;$('update-close').onclick=()=>box.close();$('update-cancel').onclick=()=>bridge?.cancel();
$('update-action').onclick=async()=>{try{if(state.phase==='ready'){const room=window.neonRoom?.();if(room?.code||room?.state==='match'){$('update-detail').textContent='Leave your room or finish your practice match before restarting.';return;}if(bridge)await bridge.install();else{activating=true;registration.waiting?.postMessage('ACTIVATE');}}else if(state.phase==='available'&&bridge)await bridge.download();else if(bridge)await bridge.check();else await browserCheck();}catch(e){render({...state,phase:'error',error:e.message});}};
if(bridge){bridge.onState(render);bridge.onOpen(open);bridge.state().then(render);}
else if('serviceWorker'in navigator&&location.protocol==='https:'){
 navigator.serviceWorker.register('./sw.js').then(reg=>{registration=reg;const ready=()=>{if(reg.waiting)render({...state,phase:'ready',notes:'A new browser build is ready. Reload when you are done playing.'});};ready();reg.addEventListener('updatefound',()=>{const installing=reg.installing;installing?.addEventListener('statechange',()=>{if(installing.state==='installed'){ready();if(!reg.waiting)render({...state,phase:'current'});}});});reg.update().catch(()=>{});}).catch(e=>render({...state,phase:'error',error:e.message}));navigator.serviceWorker.addEventListener('controllerchange',()=>{if(activating)location.reload();});
}render(state);
window.neonUpdates={open};
