import {MODES,MAPS} from './rules.js';
const $=id=>document.getElementById(id);
const modeInfo={duel:['01','Head to head','A focused duel for two. First to the score limit wins.'],dm:['02','Every player for themselves','Free-for-all combat. Make every elimination count.'],tdm:['03','Win together','Two teams, shared scores, friendly fire off. Uneven teams are welcome.'],hill:['04','Control the objective','Capture the rotating hill. Contested time earns no points.'],instagib:['05','One shot. One elimination.','Precision rifles only. Land your shot before your opponent does.'],shotgun:['06','Close the distance','Shotguns only. Use cover, slides and flanks to get within reach.']};
export function mountVisualChoices(){
 const bindings=[];let target=null,opener=null;
 const dialog=document.createElement('dialog');dialog.id='mode-picker';dialog.innerHTML='<div class="settings-heading"><div><p class="overline">FIND YOUR NEXT ROUND</p><h2>Choose a mode.</h2></div><button type="button" class="icon-button" aria-label="Close mode selection">×</button></div><p class="choice-intro">Choose how you compete. In-engine scenes show the arena style; any mode can use any map.</p><div class="mode-grid"></div>';document.body.append(dialog);const closeMode=()=>{dialog.close();opener?.focus();};dialog.querySelector('.icon-button').onclick=closeMode;dialog.addEventListener('cancel',e=>{e.preventDefault();closeMode();});dialog.addEventListener('close',()=>opener?.focus());
 for(const [id,name]of Object.entries(MODES).sort((a,b)=>modeInfo[a[0]][0].localeCompare(modeInfo[b[0]][0]))){const b=document.createElement('button'),[number,tag,description]=modeInfo[id];b.type='button';b.className='mode-card mode-'+id;b.dataset.mode=id;b.innerHTML='<span class="mode-art" aria-hidden="true"><img src="./previews/mode-'+id+'.jpg" alt=""><span>'+number+'</span></span><span class="mode-card-copy"><small>'+tag+'</small><strong>'+name+'</strong><span>'+description+'</span><em></em></span>';b.onclick=()=>{if(!target||target.disabled)return;target.value=id;target.dispatchEvent(new Event('change',{bubbles:true}));sync();closeMode();};dialog.querySelector('.mode-grid').append(b);}
 function openMode(select,button){target=select;opener=button;for(const b of dialog.querySelectorAll('[data-mode]')){b.setAttribute('aria-pressed',String(b.dataset.mode===select.value));b.querySelector('em').textContent=b.dataset.mode===select.value?'✓ SELECTED':'CHOOSE MODE →';}dialog.showModal();dialog.querySelector('[aria-pressed=true]')?.focus();}
 for(const id of ['room-mode','live-mode']){const select=$(id),b=document.createElement('button');b.type='button';b.className='mode-launch';b.id=id+'-visual';select.hidden=true;select.after(b);b.onclick=()=>openMode(select,b);bindings.push(()=>{const info=modeInfo[select.value];b.innerHTML='<span class="mode-launch-icon" aria-hidden="true">'+info[0]+'</span><span><small>'+info[1]+'</small><strong>'+MODES[select.value]+'</strong></span><em>CHANGE →</em>';b.disabled=select.disabled;});}
 const ids=['room-capacity','live-capacity','live-time','live-respawn','live-weapon','live-rotation','live-map',...Array.from(document.querySelectorAll('#settings select'),s=>s.id)];
 for(const id of ids){const select=$(id);if(!select)continue;select.hidden=true;const group=document.createElement('div');group.className='choice-group';group.id=id+'-visual';group.setAttribute('role','group');group.setAttribute('aria-label',document.querySelector('label[for="'+id+'"]')?.textContent||id);select.after(group);const buttons=[];for(const option of select.options){const b=document.createElement('button');b.type='button';b.dataset.value=option.value;b.className='choice-button';if(id==='live-map'){b.classList.add('choice-map');const img=document.createElement('img');img.src='./previews/map-'+option.value+'.png';img.alt='';b.append(img);}if(id==='live-weapon'&&+option.value>=0){const img=document.createElement('img');img.src='./previews/gun-'+option.value+'.png';img.alt='';b.classList.add('choice-weapon');b.append(img);}const label=document.createElement('span');let text=option.textContent;if(id.includes('capacity'))text=option.value;if(id==='live-weapon'&&option.value==='-1')text='Custom weapon pool';label.textContent=text;b.append(label);b.onclick=()=>{if(select.disabled)return;select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}));sync();};group.append(b);buttons.push([b,option]);}bindings.push(()=>{group.classList.toggle('choice-disabled',select.disabled);for(const [b,o]of buttons){b.disabled=select.disabled||o.disabled;b.hidden=o.hidden;b.setAttribute('aria-pressed',String(select.value===o.value));}});if(id.includes('capacity')){const hint=document.createElement('p');hint.className='choice-hint';hint.textContent='Maximum slots, not a minimum. Start with whoever is here.';group.after(hint);}if(id==='live-map'){const preview=select.parentElement.querySelector('.text-button');if(preview)preview.hidden=true;}}
 const pool=document.querySelector('.weapon-pool');for(const label of pool.querySelectorAll('label')){const input=label.querySelector('input'),img=document.createElement('img');img.src='./previews/gun-'+input.dataset.allowed+'.png';img.alt='';label.prepend(img);label.classList.add('weapon-toggle');}pool.classList.add('visual-pool');
 const rules=$('live-rules'),tabs=document.createElement('nav');tabs.className='account-tabs room-setting-tabs';tabs.setAttribute('aria-label','Room settings categories');const panes={Arena:document.createElement('section'),Rules:document.createElement('section'),Weapons:document.createElement('section')};panes.Arena.append(rules.querySelector('.room-options'));const weaponField=$('live-weapon').parentElement;panes.Rules.append(rules.querySelector('.rule-fields'));panes.Weapons.append(weaponField,pool);for(const [name,pane]of Object.entries(panes)){pane.id='room-settings-'+name.toLowerCase();pane.hidden=name!=='Arena';const b=document.createElement('button');b.type='button';b.textContent=name.toUpperCase();b.setAttribute('aria-pressed',String(name==='Arena'));b.onclick=()=>{for(const [key,p]of Object.entries(panes))p.hidden=key!==name;for(const other of tabs.children)other.setAttribute('aria-pressed',String(other===b));};tabs.append(b);}rules.querySelector('.field-label').after(tabs,...Object.values(panes));
 const status=document.createElement('p');status.className='choice-hint';status.id='room-choice-summary';$('room-mode-visual').after(status);bindings.push(()=>{status.textContent=$('room-mode').value==='duel'?'Two slots · head-to-head combat':'Up to '+$('room-capacity').value+' players · '+($('room-mode').value==='tdm'?'team play':'individual scores');});
 function sync(){bindings.forEach(fn=>fn());}let queued=false;const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;sync();});};document.addEventListener('change',schedule);window.addEventListener('neon-room-render',schedule);window.addEventListener('neon-account',schedule);const observer=new MutationObserver(schedule);for(const id of [...ids,'room-mode','live-mode'])if($(id))observer.observe($(id),{attributes:true,attributeFilter:['disabled']});
 // Keep selection buttons native so keyboard and controller menu navigation use the same controls.
 sync();
}
